'use strict';
const ledgerPages=['credit-entry','debit-entry','cash-report','debit-report','balance-report'];
const ordinaryPage=renderPage;
let accountDraft=null,accountKind='credit',selectedFile=null,range=null;
const blankRow=()=>({date:'',amount:'',remarks:''});
const money=cents=>(cents/100).toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2});
const ledger=()=>state.ledger||{credit:[],debit:[]};
const dateKey=date=>normalizeDate(date).split('/').reverse().join('-');
function amountCents(value){const normalized=String(value).trim().replace(/[০-৯]/g,c=>'০১২৩৪৫৬৭৮৯'.indexOf(c)).replace(/,/g,'');if(!/^\d+(\.\d{1,2})?$/.test(normalized))throw Error('Amount must be positive or zero, with at most two decimal places.');const [whole,fraction='']=normalized.split('.');const cents=Number(whole)*100+Number(fraction.padEnd(2,'0'));if(!Number.isSafeInteger(cents)||cents>1000000000000)throw Error('Amount is too large.');return cents;}
function accountActions(){return '<div class="account-actions no-print"><button data-account-action="print" class="print-action">Print</button><button data-account-action="edit" class="edit-action">Edit</button><button data-account-action="excel" class="excel-action">Excel</button><button data-account-action="delete" class="delete-action">Delete</button></div>';}
function signatures(){return '<div class="signatures"><span>Account</span><span>GM</span><span>MD</span></div>';}
function companyReport(title){return `<div class="report-company"><h3>FARNOOR GARMENTS LTD.</h3><p>1028/1/2 MALIBAGH BAZAR ROAD, DHAKA-1217</p></div><div class="live-clock"></div><h2 class="account-title">${title}</h2>`;}
function tickClock(){document.querySelectorAll('.live-clock').forEach(el=>el.textContent=new Date().toLocaleString('en-GB',{timeZone:'Asia/Dhaka',hour12:false}));}
setInterval(tickClock,1000);
renderPage=function(){if(!ledgerPages.includes(activePage)){ordinaryPage();return;}if(activePage.endsWith('-entry')){accountKind=activePage.startsWith('credit')?'credit':'debit';if(!accountDraft||accountDraft.kind!==accountKind)accountDraft={kind:accountKind,id:null,rows:Array.from({length:5},blankRow)};renderAccountEntry();}else if(activePage==='balance-report')renderBalance();else{accountKind=activePage==='cash-report'?'credit':'debit';renderAccountReport();}};
function draftTable(){return `<div class="table-wrap"><table class="account-table"><thead><tr><th>SL</th><th>DATE</th><th>AMOUNT</th><th>TOTAL AMOUNT</th><th>REMARKS</th><th class="row-delete no-print" aria-label="Delete row"></th></tr></thead><tbody>${accountDraft.rows.map((row,index)=>`<tr><td>${index+1}</td><td><input data-row="${index}" data-col="0" aria-label="Row ${index+1} date" value="${esc(row.date)}" placeholder="1/1/26"></td><td><input data-row="${index}" data-col="1" aria-label="Row ${index+1} amount" inputmode="decimal" value="${esc(row.amount)}"></td><td><input data-row="${index}" data-col="2" aria-label="Row ${index+1} total amount" readonly value="${esc(row.amount)}"></td><td><input data-row="${index}" data-col="3" aria-label="Row ${index+1} remarks" maxlength="500" value="${esc(row.remarks)}"></td><td class="row-delete no-print"><button data-remove-row="${index}" aria-label="Delete row ${index+1}">−</button></td></tr>`).join('')}</tbody></table></div>`;}
function renderAccountEntry(){const title=accountKind==='credit'?'CREDIT ENTRY':'DEBIT ENTRY';$('#main').innerHTML=`${accountActions()}<section class="account-paper printable">${companyReport(title)}<p class="file-caption">${accountDraft.id?'Editing saved file '+esc(accountDraft.id):'New file · Five starting rows'}</p>${draftTable()}<div class="entry-controls no-print"><button data-account-action="new">New file</button><button data-account-action="row">+ Row</button><button id="accountSave" data-account-action="save" class="primary">Save</button></div>${signatures()}</section><p class="notice no-print">Enter moves one cell right; after the final cell it moves to the next row. Arrow keys move between cells. TOTAL AMOUNT mirrors AMOUNT. Saved files appear newest first in ${accountKind==='credit'?'CASH REPORT':'DEBIT REPORT'}.</p>`;tickClock();}
function inheritDate(index){const row=accountDraft.rows[index];if(!row.date&&index>0)row.date=accountDraft.rows[index-1].date;if(row.date)row.date=normalizeDate(row.date);const input=$(`[data-row="${index}"][data-col="0"]`);if(input)input.value=row.date;}
async function saveAccount(){try{const rows=accountDraft.rows.filter(row=>row.date||row.amount||row.remarks).map(row=>{if(!row.date||row.amount==='')throw Error('Every filled row needs DATE and AMOUNT.');return {date:normalizeDate(row.date),cents:amountCents(row.amount),remarks:row.remarks.trim()};});if(!rows.length)throw Error('Enter at least one row before saving.');const next=structuredClone(state);next.ledger||={credit:[],debit:[]};const existing=next.ledger[accountKind].find(file=>file.id===accountDraft.id);const file={id:accountDraft.id||`${accountKind.toUpperCase()}-${Date.now()}-${crypto.randomUUID().slice(0,6)}`,createdAt:existing?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),rows};const index=next.ledger[accountKind].findIndex(f=>f.id===file.id);if(index>=0)next.ledger[accountKind][index]=file;else next.ledger[accountKind].unshift(file);if(await commit(next)){selectedFile=file.id;accountDraft=null;goPage(accountKind==='credit'?'cash-report':'debit-report');toast('File saved');}}catch(error){toast(error.message);}}
function entryRowsTable(rows){return `<div class="table-wrap"><table><thead><tr><th>SL</th><th>DATE</th><th>AMOUNT</th><th>TOTAL AMOUNT</th><th>REMARKS</th></tr></thead><tbody>${rows.map((row,i)=>`<tr><td>${i+1}</td><td>${esc(row.date)}</td><td>${money(row.cents)}</td><td>${money(row.cents)}</td><td class="remarks-cell">${esc(row.remarks)}</td></tr>`).join('')}</tbody><tfoot><tr><th colspan="2">TOTAL (BDT)</th><th>${money(rows.reduce((sum,r)=>sum+r.cents,0))}</th><th>${money(rows.reduce((sum,r)=>sum+r.cents,0))}</th><th></th></tr></tfoot></table></div>`;}
function renderAccountReport(){const files=ledger()[accountKind];if(!files.some(f=>f.id===selectedFile))selectedFile=files[0]?.id||null;const file=files.find(f=>f.id===selectedFile);$('#main').innerHTML=accountActions()+`<div class="saved-files no-print"><h3>Saved files · newest first</h3>${files.map(f=>`<button data-file="${esc(f.id)}" class="${selectedFile===f.id?'selected-file':''}">${esc(f.id)}<small>${new Date(f.createdAt).toLocaleString('en-GB',{timeZone:'Asia/Dhaka'})} · ${f.rows.length} rows · BDT ${money(f.rows.reduce((s,r)=>s+r.cents,0))}</small></button>`).join('')||'<p>No saved files yet.</p>'}<button data-account-action="new">+ New entry</button></div><section class="account-paper printable">${companyReport(accountKind==='credit'?'CASH REPORT':'DEBIT REPORT')}${file?`<p class="file-caption">${esc(file.id)}</p>${entryRowsTable(file.rows)}`:'<div class="empty">Save an entry to see its report here.</div>'}${signatures()}</section>`;tickClock();}
function transactions(kind){return ledger()[kind].flatMap(file=>file.rows.map((r,index)=>({...r,fileId:file.id,index,kind,createdAt:file.createdAt}))).filter(r=>!range||(dateKey(r.date)>=range.from&&dateKey(r.date)<=range.to)).sort((a,b)=>dateKey(a.date).localeCompare(dateKey(b.date))||a.createdAt.localeCompare(b.createdAt)||a.index-b.index);}
function balanceRows(){const credits=transactions('credit'),debits=transactions('debit');return Array.from({length:Math.max(credits.length,debits.length)},(_,i)=>({credit:credits[i],debit:debits[i],balance:(credits[i]?.cents||0)-(debits[i]?.cents||0)}));}
function renderBalance(){const rows=balanceRows();$('#main').innerHTML=accountActions()+`<form id="balanceSearch" class="balance-search no-print"><label>From DATE<input name="from" placeholder="1/1/26" value="${esc(range?.fromDisplay||'')}"></label><label>To DATE<input name="to" placeholder="31/12/26" value="${esc(range?.toDisplay||'')}"></label><button class="primary">Search</button><button type="button" data-account-action="clear">Clear</button></form><section class="account-paper printable ${range?'filtered-report':''}"><div class="report-identity">${companyReport('BALANCE REPORT')}</div><div class="table-wrap"><table id="balanceTable"><thead><tr><th>SL</th><th>CREDIT</th><th>CREDIT DATE</th><th>DEBIT</th><th>DEBIT DATE</th><th>BALANCE</th><th>REMARKS</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td><label><input class="balance-select no-print" type="checkbox" value="${i}" aria-label="Select balance row ${i+1}">${i+1}</label></td><td>${r.credit?money(r.credit.cents):'—'}</td><td>${esc(r.credit?.date||'—')}</td><td>${r.debit?money(r.debit.cents):'—'}</td><td>${esc(r.debit?.date||'—')}</td><td>${money(r.balance)}</td><td class="remarks-cell">${esc([r.credit?.remarks,r.debit?.remarks].filter(Boolean).join(' / '))}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">No saved transactions in this date range.</td></tr>'}</tbody><tfoot><tr><th>TOTAL</th><th>${money(rows.reduce((s,r)=>s+(r.credit?.cents||0),0))}</th><th></th><th>${money(rows.reduce((s,r)=>s+(r.debit?.cents||0),0))}</th><th></th><th>${money(rows.reduce((s,r)=>s+r.balance,0))}</th><th></th></tr></tfoot></table></div><div class="report-signatures">${signatures()}</div></section><p class="notice no-print">Rows pair CREDIT and DEBIT entries in date order. Each BALANCE is that row’s CREDIT minus DEBIT. The total is all displayed CREDIT minus all displayed DEBIT. Select one row to Edit its source file; select rows to Delete their source transactions.</p>`;tickClock();$('#balanceSearch').onsubmit=async e=>{e.preventDefault();try{const form=new FormData(e.target),from=normalizeDate(form.get('from')),to=normalizeDate(form.get('to'));if(dateKey(from)>dateKey(to))throw Error('From DATE must be on or before To DATE.');range={from:dateKey(from),to:dateKey(to),fromDisplay:from,toDisplay:to};renderBalance();}catch(error){toast(error.message);}};}
function editFile(kind,id){const file=ledger()[kind].find(f=>f.id===id);if(!file){toast('Select a saved file first.');return;}accountKind=kind;accountDraft={kind,id:file.id,rows:file.rows.map(r=>({date:r.date,amount:(r.cents/100).toFixed(2),remarks:r.remarks}))};goPage(kind+'-entry');}
async function confirmLedgerDelete(callback){const dialog=$('#deleteDialog');dialog.querySelector('h2').textContent='Delete selected account data?';dialog.querySelector('p').textContent='This deletes the selected file or transactions and updates BALANCE REPORT. Download a backup first if you need a copy.';dialog.showModal();dialog.onclose=async ()=>{if(dialog.returnValue==='delete')callback();};}
function checkedBalance(){return [...document.querySelectorAll('.balance-select:checked')].map(el=>balanceRows()[Number(el.value)]);}
$('#main').addEventListener('input',e=>{const input=e.target;if(!input.matches('[data-row]'))return;const row=accountDraft.rows[Number(input.dataset.row)],col=Number(input.dataset.col);row[['date','amount',null,'remarks'][col]]=input.value;if(col===1)$(`[data-row="${input.dataset.row}"][data-col="2"]`).value=input.value;});
$('#main').addEventListener('focusout',e=>{if(e.target.matches('[data-col="0"]')){try{inheritDate(Number(e.target.dataset.row));}catch(error){toast(error.message);}}});
$('#main').addEventListener('keydown',e=>{if(!e.target.matches('[data-row]'))return;const row=Number(e.target.dataset.row),col=Number(e.target.dataset.col);let r=row,c=col;if(e.key==='Enter'){e.preventDefault();try{if(col===0)inheritDate(row);}catch(error){toast(error.message);return;}c++;if(c>3){c=0;r++;}if(r>=accountDraft.rows.length){$('#accountSave').focus();return;}}else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();if(e.key==='ArrowLeft')c--;if(e.key==='ArrowRight')c++;if(e.key==='ArrowUp')r--;if(e.key==='ArrowDown')r++;}else return;$(`[data-row="${r}"][data-col="${c}"]`)?.focus();});
$('#main').addEventListener('click',async e=>{const button=e.target.closest('button');if(!button)return;if(button.dataset.removeRow!==undefined){accountDraft.rows.splice(Number(button.dataset.removeRow),1);if(!accountDraft.rows.length)accountDraft.rows.push(blankRow());renderAccountEntry();return;}if(button.dataset.file){selectedFile=button.dataset.file;renderAccountReport();return;}const action=button.dataset.accountAction;if(!action)return;
 if(action==='save')saveAccount();
 if(action==='row'){accountDraft.rows.push(blankRow());renderAccountEntry();}
 if(action==='new'){if(accountDraft&&accountDraft.rows.some(r=>r.date||r.amount||r.remarks)&&!confirm('Discard the current unsaved entry and start a new file?'))return;accountDraft={kind:accountKind,id:null,rows:Array.from({length:5},blankRow)};goPage(accountKind+'-entry');}
 if(action==='clear'){range=null;renderBalance();}
 if(action==='print')window.print();
 if(action==='edit'){if(activePage==='balance-report'){const selected=checkedBalance();if(selected.length!==1){toast('Select exactly one balance row to edit.');return;}const row=selected[0];let source=row.credit||row.debit;if(row.credit&&row.debit){const kind=prompt('Type CREDIT or DEBIT to choose the source file to edit.','CREDIT');if(!kind)return;if(!['CREDIT','DEBIT'].includes(kind.toUpperCase())){toast('Enter CREDIT or DEBIT.');return;}source=kind.toUpperCase()==='CREDIT'?row.credit:row.debit;}editFile(source.kind,source.fileId);}else if(activePage.endsWith('-entry')){if(accountDraft.id)editFile(accountKind,accountDraft.id);else toast('This new file is already editable.');}else editFile(accountKind,selectedFile);}
 if(action==='delete'){if(activePage==='balance-report'){const selected=checkedBalance();if(!selected.length){toast('Select balance rows to delete.');return;}await confirmLedgerDelete(async ()=>{const next=structuredClone(state);for(const kind of ['credit','debit'])next.ledger[kind]=next.ledger[kind].map(f=>({...f,rows:f.rows.filter((r,index)=>!selected.some(row=>row[kind]?.fileId===f.id&&row[kind]?.index===index))})).filter(f=>f.rows.length);if(await commit(next)){renderBalance();toast('Selected transactions deleted');}});}else{const id=activePage.endsWith('-entry')?accountDraft.id:selectedFile;if(!id){toast('Save or select a file before deleting.');return;}await confirmLedgerDelete(async ()=>{const next=structuredClone(state);next.ledger[accountKind]=next.ledger[accountKind].filter(f=>f.id!==id);if(await commit(next)){accountDraft=null;selectedFile=null;goPage(accountKind==='credit'?'cash-report':'debit-report');toast('File deleted');}});}}
 if(action==='excel'){try{let matrix,title;if(activePage==='balance-report'){title='BALANCE REPORT';matrix=[['SL','CREDIT','CREDIT DATE','DEBIT','DEBIT DATE','BALANCE','REMARKS'],...balanceRows().map((r,i)=>[i+1,(r.credit?.cents||0)/100,r.credit?.date||'',(r.debit?.cents||0)/100,r.debit?.date||'',r.balance/100,[r.credit?.remarks,r.debit?.remarks].filter(Boolean).join(' / ')])];}else{title=activePage.endsWith('-entry')?(accountKind==='credit'?'CREDIT ENTRY':'DEBIT ENTRY'):(accountKind==='credit'?'CASH REPORT':'DEBIT REPORT');const rows=activePage.endsWith('-entry')?accountDraft.rows.filter(r=>r.date||r.amount||r.remarks).map(r=>({date:normalizeDate(r.date),cents:amountCents(r.amount),remarks:r.remarks})):ledger()[accountKind].find(f=>f.id===selectedFile)?.rows||[];matrix=[['SL','DATE','AMOUNT','TOTAL AMOUNT','REMARKS'],...rows.map((r,i)=>[i+1,r.date,r.cents/100,r.cents/100,r.remarks])];}if(matrix.length===1){toast('No rows to export.');return;}download(title.toLowerCase().replaceAll(' ','-')+'.xlsx',makeXlsx(matrix,title),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');toast('Excel file downloaded');}catch(error){toast(error.message);}}
});
