'use strict';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='farnoor.workspace.v1';
const statuses=['Pending','In progress','Completed','Cancelled'];
function normalizeDate(value){
 const raw=String(value).trim().replace(/[০-৯]/g,c=>'০১২৩৪৫৬৭৮৯'.indexOf(c));
 const match=raw.match(/^(\d{1,2})[/.\-](\d{1,2})[/.\-](\d{2}|\d{4})$/);
 if(!match)throw Error('Use a date like 1/1/26 or 01/01/2026.');
 const day=Number(match[1]),month=Number(match[2]),year=match[3].length===2?2000+Number(match[3]):Number(match[3]);
 const test=new Date(year,month-1,day);
 if(year<1900||year>2199||test.getFullYear()!==year||test.getMonth()!==month-1||test.getDate()!==day)throw Error('Please enter a valid date.');
 return `${String(day).padStart(2,'0')}/${String(month).padStart(2,'0')}/${year}`;
}
function initialState(){return {profile:{username:'Farnoor Admin',email:'admin@farnoor.example',photo:''},records:{}};}
function validateState(data){
 if(!data||!data.profile||typeof data.profile.username!=='string'||!data.profile.username.trim()||data.profile.username.length>60||typeof data.profile.email!=='string'||!/^\S+@\S+\.\S+$/.test(data.profile.email)||data.profile.email.length>120||typeof data.profile.photo!=='string'||(data.profile.photo&&!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(data.profile.photo))||data.profile.photo.length>2800000||!data.records||typeof data.records!=='object'||Array.isArray(data.records))throw Error('Invalid backup file.');
 for(const department of DEPARTMENTS)for(const page of department.pages){const rows=data.records[page.id]||[];if(!Array.isArray(rows)||rows.length>10000)throw Error('Invalid records.');const ids=new Set();for(const row of rows){if(typeof row.id!=='string'||ids.has(row.id)||typeof row.reference!=='string'||typeof row.name!=='string'||row.reference.length>120||row.name.length>200||!Number.isFinite(Number(row.quantity))||Number(row.quantity)<0||!statuses.includes(row.status))throw Error('Invalid record in backup.');normalizeDate(row.date);ids.add(row.id);}}
 if(data.ledger){for(const kind of ['credit','debit']){if(!Array.isArray(data.ledger[kind])||data.ledger[kind].length>10000)throw Error('Invalid account files.');for(const file of data.ledger[kind]){if(typeof file.id!=='string'||file.id.length>120||typeof file.createdAt!=='string'||!Number.isFinite(Date.parse(file.createdAt))||!Array.isArray(file.rows)||file.rows.length>10000)throw Error('Invalid account file.');for(const row of file.rows){normalizeDate(row.date);if(!Number.isSafeInteger(row.cents)||row.cents<0||typeof row.remarks!=='string'||row.remarks.length>500)throw Error('Invalid account row.');}}}}
 if(data.orderFiles){if(!Array.isArray(data.orderFiles)||data.orderFiles.length>10000)throw Error('Invalid order files.');const ids=new Set();for(const file of data.orderFiles){if(typeof file.id!=='string'||file.id.length>120||ids.has(file.id)||!Number.isFinite(Date.parse(file.createdAt))||!Array.isArray(file.rows)||file.rows.length>10000)throw Error('Invalid order file.');ids.add(file.id);for(const row of file.rows){for(const key of ['buyer','style','item','remarks'])if(typeof row[key]!=='string'||row[key].length>500)throw Error('Invalid order details.');if(!Number.isSafeInteger(row.qty)||row.qty<1)throw Error('Invalid order quantity.');normalizeDate(row.orderDate);normalizeDate(row.shipmentDate);}}}
 if(data.productionSchedules){if(!Array.isArray(data.productionSchedules)||data.productionSchedules.length>10000)throw Error('Invalid production schedules.');const ids=new Set();for(const file of data.productionSchedules){if(typeof file.id!=='string'||ids.has(file.id)||file.id.length>120||!DEPARTMENTS.flatMap(d=>d.pages).some(p=>p.section===file.section)||!Number.isFinite(Date.parse(file.createdAt))||typeof file.month!=='string'||!/^\d{1,2}\/\d{4}$/.test(file.month)||!['None','Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].includes(file.weekly)||!Array.isArray(file.extra)||file.extra.some(day=>!Number.isInteger(day)||day<1||day>31)||!Array.isArray(file.rows)||file.rows.length>10000||!file.journal||typeof file.journal!=='object'||Array.isArray(file.journal))throw Error('Invalid saved production plan.');const [month,year]=file.month.split('/').map(Number);if(month<1||month>12||year<1900||year>2199||file.extra.some(day=>day>new Date(year,month,0).getDate()))throw Error('Invalid production month.');ids.add(file.id);for(const row of file.rows){for(const key of ['buyer','item','style','remarks'])if(typeof row[key]!=='string'||row[key].length>500)throw Error('Invalid production details.');for(const key of ['orderQty','totalQty','firstTarget','dailyTarget'])if(!Number.isSafeInteger(row[key])||row[key]<0||row[key]>1000000000)throw Error('Invalid production quantity.');normalizeDate(row.startDate);}for(const [date,actual]of Object.entries(file.journal)){normalizeDate(date);if(!actual||typeof actual!=='object'||String(actual.remarks||'').length>500||!Number.isFinite(Number(actual.hours??10))||Number(actual.hours??10)<=0||Number(actual.hours??10)>24||!/^[০-৯0-9,]*$/.test(String(actual.output||'')))throw Error('Invalid daily output.');}}}
 window.FarnoorPayrollCore?.validateRows(data.records.payroll,normalizeDate);
 return data;
}
let state=initialState();let storageWarning='';
let activePage=null,opened=new Set(),query='',filter='All statuses',editingId=null,pendingPhoto='',sessionActive=false;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('visible'),4500);}
function avatar(photo,name){return photo?`<img class="avatar-image" src="${esc(photo)}" alt="User photo">`:`<span class="avatar-initial">${esc(name.slice(0,1).toUpperCase())}</span>`;}
function renderProfile(){$('#username').textContent=state.profile.username;$('#avatar').innerHTML=avatar(state.profile.photo,state.profile.username);}
function pageInfo(id){for(const department of DEPARTMENTS){const page=department.pages.find(p=>p.id===id);if(page)return {department,page};}return null;}
const submenuLooks=new Map();
const departmentHues={admin:195,packing:95,sewing:330,hr:333,accounts:150,commercial:215,merch:265,knitting:185,inventory:38,production:200,cutting:18,finishing:300,quality:80,sample:348,maintenance:215,electrical:48};
for(const department of DEPARTMENTS){
 const keys=new Set();
 for(const page of department.pages.filter(p=>!p.hidden)){
  if(!page.groupEntry)keys.add('page:'+page.id);
  if(page.parent)keys.add('group:'+department.id+':'+page.parent);
  page.navPath?.forEach((part,index)=>keys.add('group:'+department.id+':'+page.navPath.slice(0,index+1).join('/')));
 }
 for(const key of keys){
  const index=submenuLooks.size;let hue=Math.round(index*137.508)%360;
  const distance=Math.abs(hue-departmentHues[department.id]);
  if(Math.min(distance,360-distance)<65)hue=(hue+150)%360;
  const saturation=58+index%17,lightness=91+(index%5)*.7;
  submenuLooks.set(key,{hue,saturation,lightness,shape:['rounded','ticket','rail','pill','underline'][index%5]});
 }
}
function submenuAttributes(key,depth=0){
 const look=submenuLooks.get(key),{hue:h,saturation:s,lightness:l,shape}=look;
 return `data-sub-style="${shape}" data-sub-depth="${depth}" style="--sub-bg:hsl(${h} ${s}% ${l}%);--sub-edge:hsl(${h} ${s-15}% 75%);--sub-ink:hsl(${h} 42% 25%);--sub-accent:hsl(${h} 45% 48%)"`;
}
function renderNavigation(){
 const pageButton=(p,depth=0)=>`<button class="page-button ${activePage===p.id?'active':''}" data-page="${p.id}" ${submenuAttributes('page:'+p.id,depth)} aria-expanded="${activePage===p.id}"><span class="submenu-icon" aria-hidden="true">${p.icon}</span><span class="submenu-label">${esc(p.name)}</span></button>`;
 const tree=(department,pages,depth=0,path=[])=>{const seen=new Set();return pages.map(page=>{if(!page.navPath||page.navPath.length<=depth)return page.groupEntry?'':pageButton(page,depth);const label=page.navPath[depth];if(seen.has(label))return '';seen.add(label);const children=pages.filter(p=>p.navPath?.[depth]===label),nextPath=[...path,label],key=department.id+':'+nextPath.join('/'),entry=children.find(p=>p.groupEntry&&p.navPath.length===depth+1);return `<button class="page-button schedule-group" data-group="${esc(key)}" ${entry?`data-group-page="${entry.id}"`:''} ${submenuAttributes('group:'+key,depth)} aria-expanded="${opened.has(key)}"><span class="submenu-icon" aria-hidden="true">${({'Admin':'♛','Utilities':'⚒','Management':'▦','HR Info':'♙','Attendance':'◷','Schedule':'▦','Schedule Report':'▤','Sewing':'⚙'})[label]||'▥'}</span><span class="submenu-label">${esc(label)}</span><span class="submenu-toggle">${opened.has(key)?'−':'+'}</span></button>${opened.has(key)?`<div class="nested-pages">${tree(department,children,depth+1,nextPath)}</div>`:''}`;}).join('');};
 $('#navigation').innerHTML=DEPARTMENTS.filter(d=>d.pages.some(p=>!p.hidden&&(window.FarnoorAccess?.canPage(p.id)??false))).map(d=>{const seen=new Set();const pages=d.pages.filter(p=>!p.hidden&&(window.FarnoorAccess?.canPage(p.id)??false));return `<div class="department"><button class="department-button" data-department="${d.id}" style="--color:${d.color}" aria-expanded="${opened.has(d.id)}"><span class="icon" aria-hidden="true">${d.icon}</span><span>${esc(d.name)}</span><span class="chevron">${opened.has(d.id)?'−':'+'}</span></button>${opened.has(d.id)?`<div class="pages">${pages.some(p=>p.navPath)?tree(d,pages):pages.map(p=>{if(!p.parent)return pageButton(p);if(seen.has(p.parent))return '';seen.add(p.parent);const key=d.id+':'+p.parent;return `<button class="page-button account-group" data-group="${key}" ${submenuAttributes('group:'+key)} aria-expanded="${opened.has(key)}"><span class="submenu-icon" aria-hidden="true">${p.parent==='CREDIT'?'⊕':p.parent==='DEBIT'?'⊖':'▤'}</span><span class="submenu-label">${esc(p.parent)}</span><span class="submenu-toggle">${opened.has(key)?'−':'+'}</span></button>${opened.has(key)?`<div class="nested-pages">${pages.filter(child=>child.parent===p.parent).map(child=>pageButton(child,1)).join('')}</div>`:''}`;}).join('')}</div>`:''}</div>`;}).join('');
}
$('#navigation').addEventListener('click',e=>{const group=e.target.closest('[data-group]');if(!group)return;const key=group.dataset.group;if(opened.has(key)){opened.delete(key);const info=pageInfo(activePage);if(info&&(info.page.parent===key.split(':')[1]||info.page.navPath?.join('/').startsWith(key.split(':')[1]))){activePage=null;renderClosed();}}else{opened.add(key);if(group.dataset.groupPage)goPage(group.dataset.groupPage);}renderNavigation();});
function goPage(id){const info=pageInfo(id);opened.add(info.department.id);if(info.page.parent)opened.add(info.department.id+':'+info.page.parent);if(info.page.navPath)info.page.navPath.forEach((part,index)=>opened.add(info.department.id+':'+info.page.navPath.slice(0,index+1).join('/')));activePage=id;query='';filter='All statuses';renderNavigation();renderPage();}
$('#navigation').addEventListener('click',event=>{const department=event.target.closest('[data-department]'),page=event.target.closest('[data-page]');if(department){const id=department.dataset.department;if(opened.has(id)){opened.delete(id);if(activePage&&pageInfo(activePage).department.id===id){activePage=null;renderClosed();}}else opened.add(id);renderNavigation();}if(page){if(activePage===page.dataset.page){activePage=null;renderNavigation();renderClosed();}else goPage(page.dataset.page);}});
function badge(status){return `<span class="badge ${status==='Completed'?'complete':status==='Pending'?'pending':status==='Cancelled'?'cancelled':''}">${esc(status)}</span>`;}
function heading(label,title,subtitle,action=''){return `<div class="page-heading"><div><span class="eyebrow">${esc(label)}</span><h2>${esc(title)}</h2><p>${esc(subtitle)}</p></div>${action}</div>`;}
function allRecords(){return DEPARTMENTS.flatMap(d=>d.pages.flatMap(p=>(state.records[p.id]||[]).map(r=>({...r,page:p.id}))));}
function renderOverview(){
 activePage=null;renderNavigation();const orders=(state.orderFiles||[]).flatMap(file=>file.rows.map(row=>({reference:row.style,name:row.buyer+' · '+row.item,quantity:row.qty,date:row.shipmentDate,status:'Saved'}))),all=allRecords(),pending=all.filter(r=>r.status==='Pending').length;
 $('#main').innerHTML=heading('OPERATIONS OVERVIEW','Your factory, at a glance','A clear view of orders, teams and daily operations.',`<span class="date-tag">${new Date().toLocaleDateString('en-GB',{timeZone:'Asia/Dhaka'})}</span>`)+`<div class="stats">${[['Buyer orders',orders.length,'Saved order rows','#6753ab'],['Order quantity',orders.reduce((s,r)=>s+Number(r.quantity),0).toLocaleString(),'Pieces in the order register','#2d7c95'],['Employee records',(state.records.employees||[]).length,'People in the employee register','#af546d'],['Pending records',pending,'Across all departments','#b17a29']].map(([label,value,note,color])=>`<div class="stat"><span class="accent" style="--accent:${color}"></span><small>${label}</small><strong>${value}</strong><p>${note}</p></div>`).join('')}</div><section class="panel"><div class="panel-header"><h3>Buyer order register</h3><button data-open-page="order-report">View orders</button></div><div class="table-wrap"><table><thead><tr><th>ORDER</th><th>BUYER / STYLE</th><th>QUANTITY</th><th>DELIVERY</th><th>STATUS</th></tr></thead><tbody>${orders.slice(0,5).map(r=>`<tr><td>${esc(r.reference)}</td><td>${esc(r.name)}</td><td>${Number(r.quantity).toLocaleString()} pcs</td><td>${esc(r.date)}</td><td>${badge(r.status)}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No orders yet. Open Buyer orders to add one.</td></tr>'}</tbody></table></div></section><div class="overview-bottom"><section class="panel"><div class="panel-header"><h3>Department activity</h3><small>Completed records / total</small></div><div class="progress-list">${DEPARTMENTS.filter(d=>['merch','production','quality'].includes(d.id)).map(d=>{const records=d.pages.flatMap(p=>state.records[p.id]||[]),done=records.filter(r=>r.status==='Completed').length;return `<div><div class="progress-title"><span>${esc(d.name)}</span><strong>${done} / ${records.length}</strong></div><div class="track"><span style="width:${records.length?done/records.length*100:0}%;background:${d.color}"></span></div></div>`;}).join('')}</div></section><section class="panel"><div class="panel-header"><h3>Quick access</h3><small>Common registers</small></div><div class="quick-list"><button data-open-page="order-report">▤ Buyer orders <span>Open</span></button><button data-open-page="stock">▧ Fabric & trims <span>Open</span></button><button data-open-page="employees">♧ Personal File <span>Open</span></button></div></section></div><div class="notice">User workspace · Saved data is stored in the secure online database. Download a backup when needed. Right-click your user profile to edit it; on mobile, tap the profile.</div><p class="footer-note">FARNOOR GARMENTS LTD. · Management workspace · User workspace</p>`;
}
function renderClosed(){$('#main').innerHTML=`<div class="closed"><div class="symbol">▦</div><h2>Page closed</h2><p>Select a page from a department or return to the overview.</p><button id="returnOverview" class="primary">Open overview</button></div>`;}
function fields(){return pageInfo(activePage).page.fields||DEFAULT_FIELDS;}
function filteredRows(){return (state.records[activePage]||[]).filter(r=>(filter==='All statuses'||r.status===filter)&&`${r.reference} ${r.name} ${r.date} ${r.status}`.toLowerCase().includes(query.toLowerCase()));}
function renderRows(){const rows=filteredRows();$('#rows').innerHTML=rows.map(r=>`<tr>${fields().map(([key])=>`<td>${key==='status'?badge(r[key]):esc(key==='quantity'?Number(r[key]).toLocaleString():r[key])}</td>`).join('')}<td><div class="row-actions"><button data-edit="${esc(r.id)}">Edit</button><button data-delete="${esc(r.id)}" aria-label="Delete ${esc(r.reference)}">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="6" class="empty">No matching records. Add a record or adjust your filters.</td></tr>';$('#rowCount').textContent=`${rows.length} of ${(state.records[activePage]||[]).length} records`;}
function renderPage(){const {department,page}=pageInfo(activePage);$('#main').innerHTML=heading(department.name,page.name,'Manage your records. Dates are displayed as DD/MM/YYYY.','<button id="newRecord" class="primary">+ New record</button>')+`<section class="panel"><div class="toolbar"><input id="search" type="search" placeholder="Search this register…" aria-label="Search records" value="${esc(query)}"><select id="statusFilter" aria-label="Filter status">${['All statuses',...statuses].map(s=>`<option ${filter===s?'selected':''}>${s}</option>`).join('')}</select><button id="export">Export CSV</button><span id="rowCount" class="count"></span></div><div class="table-wrap"><table><thead><tr>${fields().map(([,label])=>`<th>${esc(label.toUpperCase())}</th>`).join('')}<th>ACTIONS</th></tr></thead><tbody id="rows"></tbody></table></div></section><div class="notice">User workspace · Saved records are stored in the secure online database. Date example: <strong>1/1/26 → 01/01/2026</strong>. Bengali digits are also accepted: <strong>১/১/২৬</strong>.</div>`;renderRows();$('#search').addEventListener('input',e=>{query=e.target.value;renderRows();});$('#statusFilter').addEventListener('change',e=>{filter=e.target.value;renderRows();});}
function openRecord(id=null){editingId=id;const row=(state.records[activePage]||[]).find(r=>r.id===id)||{};$('#recordTitle').textContent=id?'Edit record':'New record';$('#recordCategory').textContent=pageInfo(activePage).page.name;$('#recordFields').innerHTML=fields().map(([key,label,type])=>`<label>${esc(label)}${type==='status'?`<select name="${key}">${statuses.map(s=>`<option ${row[key]===s?'selected':''}>${s}</option>`).join('')}</select>`:`<input name="${key}" ${type==='number'?'type="number" min="0" step="any"':'type="text"'} value="${esc(row[key]??'')}" ${type==='date'?'data-date placeholder="1/1/26" inputmode="numeric"':`maxlength="${key==='name'?200:120}"`} required>`}</label>`).join('');$('#recordDialog').showModal();}
$('#recordForm').addEventListener('focusout',e=>{if(e.target.matches('[data-date]')&&e.target.value){try{e.target.value=normalizeDate(e.target.value);e.target.setCustomValidity('');}catch(error){e.target.setCustomValidity(error.message);}}});
$('#recordForm').addEventListener('input',e=>e.target.setCustomValidity?.(''));
$('#recordForm').addEventListener('submit',async e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.target));try{values.date=normalizeDate(values.date);}catch(error){toast(error.message);return;}values.reference=values.reference.trim();values.name=values.name.trim();if(!values.reference||!values.name){toast('Reference and description cannot be blank.');return;}values.quantity=Number(values.quantity);values.id=editingId||crypto.randomUUID();const next=structuredClone(state),rows=next.records[activePage]||[];if(editingId)rows[rows.findIndex(r=>r.id===editingId)]=values;else rows.push(values);next.records[activePage]=rows;if(await commit(next)){$('#recordDialog').close();renderPage();toast('Record saved');}});
$('#main').addEventListener('click',async e=>{const target=e.target.closest('button');if(!target)return;if(target.dataset.openPage)goPage(target.dataset.openPage);if(target.id==='returnOverview')renderOverview();if(target.id==='newRecord')openRecord();if(target.dataset.edit)openRecord(target.dataset.edit);if(target.dataset.delete){const id=target.dataset.delete,page=activePage;$('#deleteDialog').showModal();$('#deleteDialog').onclose=async ()=>{if($('#deleteDialog').returnValue==='delete'){const next=structuredClone(state);next.records[page]=next.records[page].filter(r=>r.id!==id);if(await commit(next)){renderPage();toast('Record deleted');}}};}if(target.id==='export')exportCSV();});
function download(filename,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportCSV(){const quote=value=>'"'+String(/^[=+@\-\t\r]/.test(String(value))?'\''+value:value).replace(/"/g,'""')+'"';const cols=fields();download(`farnoor-${activePage}.csv`,'\ufeff'+[cols.map(([,label])=>quote(label)).join(','),...filteredRows().map(r=>cols.map(([key])=>quote(r[key])).join(','))].join('\r\n'),'text/csv;charset=utf-8');toast('CSV exported');}
function openProfile(){if(!sessionActive)return;$('#profileForm').elements.username.value=state.profile.username;$('#profileForm').elements.email.value=state.profile.email;$('#profileForm').elements.photo.value='';pendingPhoto=state.profile.photo;renderPhotoPreview();$('#profileDialog').showModal();}
function renderPhotoPreview(){$('#photoPreview').innerHTML=pendingPhoto?`<img src="${esc(pendingPhoto)}" alt="Photo preview">`:'';}
$('#profileButton').addEventListener('contextmenu',e=>{e.preventDefault();openProfile();});$('#profileButton').addEventListener('click',openProfile);
let photoLoading=false;
$('#profileForm').elements.photo.addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>250*1024){toast('Choose a PNG, JPG or WebP photo under 250 KB.');e.target.value='';return;}photoLoading=true;try{pendingPhoto=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});renderPhotoPreview();}catch{toast('Could not read this photo.');}finally{photoLoading=false;}});
$('#removePhoto').onclick=()=>{pendingPhoto='';$('#profileForm').elements.photo.value='';renderPhotoPreview();};
$('#profileForm').onsubmit=async e=>{e.preventDefault();if(photoLoading){toast('Please wait for the photo to finish loading.');return;}const username=e.target.elements.username.value.trim(),email=e.target.elements.email.value.trim();if(!username){toast('Please enter a username.');return;}if(!/^\S+@\S+\.\S+$/.test(email)){toast('Please enter a complete email address.');return;}const next=structuredClone(state);next.profile={username,email,photo:pendingPhoto};if(await commit(next)){renderProfile();$('#profileDialog').close();toast('Profile updated');}};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());
$('#dashboardButton').onclick=renderOverview;
$('#backup').onclick=()=>download('farnoor-backup.json',JSON.stringify(state,null,2),'application/json');
$('#restoreButton').onclick=()=>$('#restore').click();
$('#restore').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>12*1024*1024)throw Error('Backup is too large.');const next=validateState(JSON.parse(await file.text()));if(confirm('Replace this workspace with the backup? Current records will be replaced.')){if(await commit(next)){renderProfile();renderOverview();toast('Backup restored');}}}catch(error){toast(error.message||'Could not restore backup.');}finally{e.target.value='';}};
renderProfile();renderOverview();if(storageWarning)toast(storageWarning);
// Optional browser-agent navigation. Unsupported browsers keep the ordinary UI.
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
 try{Promise.resolve(document.modelContext.registerTool({name:'open_register',title:'Open department register',description:'Open an existing Farnoor department page. Does not change saved records.',inputSchema:{type:'object',properties:{pageId:{type:'string',enum:DEPARTMENTS.flatMap(d=>d.pages.map(p=>p.id))}},required:['pageId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!sessionActive)throw Error('Workspace is logged out.');if(!input||typeof input.pageId!=='string'||!pageInfo(input.pageId)||Object.keys(input).length!==1)throw Error('Unknown page.');goPage(input.pageId);return {opened:input.pageId,title:pageInfo(input.pageId).page.name};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}
}






