'use strict';
const previousPageRenderer=renderPage;
const orderColumns=[['buyer','BUYER'],['style','STYLE'],['item','ITEM'],['qty','ORDER QTY'],['orderDate','ORDER DATE'],['shipmentDate','SHIPMENT DATE'],['remarks','REMARKS']];
let orderDraft=null,orderSelected=null,orderSearch='';
const newOrderRow=()=>({buyer:'',style:'',item:'',qty:'',orderDate:'',shipmentDate:'',remarks:''});
const orderFiles=()=>state.orderFiles||[];
function orderReportNumbers(files=orderFiles()){const numbers=new Map(),used=new Map();for(const file of files){const number=file.reportNumber||(/^FGL-\d{4}\.\d+$/.test(file.id)?file.id:null);if(number){numbers.set(file.id,number);const [year,serial]=number.slice(4).split('.');if(!used.has(year))used.set(year,new Set());used.get(year).add(Number(serial));}}for(const file of [...files].sort((a,b)=>a.createdAt.localeCompare(b.createdAt)||a.id.localeCompare(b.id))){if(numbers.has(file.id))continue;const year=new Intl.DateTimeFormat('en',{year:'numeric',timeZone:'Asia/Dhaka'}).format(new Date(file.createdAt));if(!used.has(year))used.set(year,new Set());let serial=1;while(used.get(year).has(serial))serial++;used.get(year).add(serial);numbers.set(file.id,'FGL-'+year+'.'+String(serial).padStart(4,'0'));}return numbers;}
function orderReportNumber(file){return orderReportNumbers().get(file.id)||file.id;}
function preserveOrderNumbers(files){const numbers=orderReportNumbers(files);for(const file of files)file.reportNumber=numbers.get(file.id);}
function nextOrderNumber(files){const year=new Intl.DateTimeFormat('en',{year:'numeric',timeZone:'Asia/Dhaka'}).format(new Date());const prefix='FGL-'+year+'.';const serial=Math.max(0,...[...orderReportNumbers(files).values()].filter(n=>n.startsWith(prefix)).map(n=>Number(n.slice(prefix.length))))+1;return prefix+String(serial).padStart(4,'0');}
renderPage=function(){if(activePage==='order-entry'){orderDraft||={id:null,rows:Array.from({length:5},newOrderRow)};drawOrderEntry();}else if(activePage==='order-report')drawOrderReport();else previousPageRenderer();};
function orderActions(){return '<div class="order-actions no-print"><button data-order-action="print" class="print-action">Print</button><button data-order-action="edit" class="edit-action">Edit</button><button data-order-action="excel" class="excel-action">Excel</button><button data-order-action="delete" class="delete-action">Delete</button></div>';}
function orderSignatures(){return '<div class="signatures"><span>Merchandiser</span><span>GM</span><span>MD</span></div>';}
function orderIdentity(title,file){return `<div class="order-company"><img src="Farnoor_New_Logo.png" alt="Farnoor logo"><div><h3>FARNOOR GARMENTS LTD.</h3><p>1028/1/2 MALIBAGH BAZAR ROAD, DHAKA-1217</p></div></div><div class="order-saved-clock">${file?esc(new Date(file.updatedAt||file.createdAt).toLocaleString('en-GB',{timeZone:'Asia/Dhaka'})):''}</div><h2 class="account-title">${title}</h2>`;}
function orderTable(rows,editable=false){return `<div class="table-wrap"><table class="order-table"><thead><tr><th>SL</th>${orderColumns.map(([,label])=>`<th>${label}</th>`).join('')}${editable?'<th class="row-delete no-print" aria-label="Remove row"></th>':''}</tr></thead><tbody>${rows.map((row,index)=>`<tr><td>${index+1}</td>${orderColumns.map(([key,label],col)=>`<td>${editable?`<input data-order-row="${index}" data-order-col="${col}" aria-label="Order row ${index+1} ${label}" value="${esc(row[key])}" ${key==='qty'?'inputmode="numeric"':key.endsWith('Date')?'placeholder="1/1/26"':'maxlength="500"'}>`:esc(row[key])}</td>`).join('')}${editable?`<td class="row-delete no-print"><button data-order-remove="${index}" aria-label="Remove order row ${index+1}">−</button></td>`:''}</tr>`).join('')||'<tr><td colspan="8" class="empty">No matching orders.</td></tr>'}</tbody></table></div>`;}
function drawOrderEntry(){$('#main').innerHTML=`<section class="account-paper printable order-entry-paper"><div class="order-entry-title"><h2 class="account-title">NEW ORDER</h2><input aria-label="Order number" readonly value="${esc(orderDraft.id?orderReportNumber(orderFiles().find(file=>file.id===orderDraft.id)||{id:orderDraft.id}):nextOrderNumber(orderFiles()))}"></div>${orderTable(orderDraft.rows,true)}<div class="entry-controls no-print"><button data-order-action="new">New file</button><button data-order-action="row">+ Row</button><button id="orderSave" data-order-action="save" class="primary">Save</button></div></section><p class="notice no-print">Enter moves right, then to the next row. Arrow keys change cells. After the last cell, Enter focuses Save. Dates: 1/1/26 → 01/01/2026.</p>`;}
async function saveOrder(){try{const rows=orderDraft.rows.filter(r=>Object.values(r).some(v=>String(v).trim())).map(r=>{const row=Object.fromEntries(Object.entries(r).map(([k,v])=>[k,String(v).trim()]));if(!row.buyer||!row.style||!row.item)throw Error('Every filled row needs BUYER, STYLE and ITEM.');const qty=row.qty.replace(/[০-৯]/g,c=>'০১২৩৪৫৬৭৮৯'.indexOf(c)).replaceAll(',','');if(!/^\d+$/.test(qty)||!Number.isSafeInteger(Number(qty))||Number(qty)<1)throw Error('ORDER QTY must be a positive whole number.');row.qty=Number(qty);row.orderDate=normalizeDate(row.orderDate);row.shipmentDate=normalizeDate(row.shipmentDate);if(dateKey(row.shipmentDate)<dateKey(row.orderDate))throw Error('SHIPMENT DATE cannot be before ORDER DATE.');return row;});if(!rows.length)throw Error('Enter at least one order.');const next=structuredClone(state);next.orderFiles||=[];preserveOrderNumbers(next.orderFiles);const index=next.orderFiles.findIndex(f=>f.id===orderDraft.id);const file={id:orderDraft.id||nextOrderNumber(next.orderFiles),createdAt:index>=0?next.orderFiles[index].createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),rows};file.reportNumber=index>=0?next.orderFiles[index].reportNumber:file.id;if(index>=0)next.orderFiles[index]=file;else next.orderFiles.unshift(file);if(await commit(next)){orderSelected=file.id;orderDraft=null;orderSearch='';goPage('order-report');toast('Order file saved');}}catch(error){toast(error.message);}}
function filteredOrderRows(){const terms=orderSearch.toLowerCase().trim().split(/\s+/).filter(Boolean);return orderFiles().flatMap(file=>file.rows.map(row=>({...row,fileId:file.id}))).filter(row=>terms.every(term=>`${row.buyer} ${row.style} ${row.item}`.toLowerCase().includes(term)));}
function drawOrderReport(){const files=orderFiles();if(!files.some(f=>f.id===orderSelected))orderSelected=files[0]?.id||null;$('#main').innerHTML=`<form id="orderSearchForm" class="order-search no-print"><label>Search BUYER / STYLE / ITEM<input id="orderSearchInput" type="search" list="orderSuggestions" autocomplete="off" placeholder="Type at least two letters or numbers…" value="${esc(orderSearch)}"><datalist id="orderSuggestions"></datalist></label><button class="primary">Search</button><button type="button" data-order-action="clear">Clear</button></form>${orderSearch?`${orderActions()}<section class="account-paper printable order-search-results">${orderTable(filteredOrderRows())}</section>`:`<div class="no-print order-file-picker"><label><select aria-label="Saved order file" id="orderFileSelect">${files.map(file=>`<option value="${esc(file.id)}" ${file.id===orderSelected?'selected':''}>${esc(orderReportNumber(file))} · ${file.rows.length} rows</option>`).join('')||'<option>No saved files</option>'}</select></label><button data-order-action="new">+ New order</button></div>${orderActions()}<div class="order-saved-list">${files.map(file=>`<section class="account-paper printable order-document ${file.id===orderSelected?'selected-order':''}" data-order-file="${esc(file.id)}"><div class="no-print file-controls"><button data-select-order="${esc(file.id)}">${file.id===orderSelected?'Selected file':'Select file'}</button><small>Saved ${new Date(file.createdAt).toLocaleString('en-GB',{timeZone:'Asia/Dhaka'})}</small></div>${orderIdentity('ORDER REPORT',file)}<p class="file-caption">${esc(orderReportNumber(file))}</p>${orderTable(file.rows)}${orderSignatures()}</section>`).join('')||'<div class="empty">No saved order files. Open ORDER ENTRY to add an order.</div>'}</div>`}`;tickClock();$('#orderSearchForm').onsubmit=async e=>{e.preventDefault();const value=$('#orderSearchInput').value.trim();if(value&&value.length<2){toast('Type at least two letters or numbers.');return;}orderSearch=value;drawOrderReport();};$('#orderSearchInput').oninput=e=>{const value=e.target.value.toLowerCase().trim();const suggestions=value.length>=2?[...new Set(files.flatMap(f=>f.rows.flatMap(r=>[r.buyer,r.style,r.item])))].filter(text=>text.toLowerCase().includes(value)).slice(0,30):[];$('#orderSuggestions').innerHTML=suggestions.map(s=>`<option value="${esc(s)}"></option>`).join('');};const selector=$('#orderFileSelect');if(selector)selector.onchange=e=>{orderSelected=e.target.value;drawOrderReport();};}
function editOrder(id){const file=orderFiles().find(f=>f.id===id);if(!file){toast('Select a saved order file first.');return;}orderDraft={id:file.id,rows:file.rows.map(row=>({...row,qty:String(row.qty)}))};goPage('order-entry');}
$('#main').addEventListener('input',e=>{if(!e.target.matches('[data-order-row]'))return;const input=e.target;orderDraft.rows[Number(input.dataset.orderRow)][orderColumns[Number(input.dataset.orderCol)][0]]=input.value;});
$('#main').addEventListener('focusout',e=>{if(!e.target.matches('[data-order-col="4"],[data-order-col="5"]')||!e.target.value)return;try{const input=e.target,value=normalizeDate(input.value);input.value=value;orderDraft.rows[Number(input.dataset.orderRow)][orderColumns[Number(input.dataset.orderCol)][0]]=value;}catch(error){toast(error.message);}});
$('#main').addEventListener('keydown',e=>{if(!e.target.matches('[data-order-row]'))return;let row=Number(e.target.dataset.orderRow),col=Number(e.target.dataset.orderCol);if(e.key==='Enter'){e.preventDefault();if([4,5].includes(col)&&e.target.value){try{normalizeDate(e.target.value);}catch(error){toast(error.message);return;}}col++;if(col===orderColumns.length){col=0;row++;}if(row===orderDraft.rows.length){$('#orderSave').focus();return;}}else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();if(e.key==='ArrowLeft')col--;if(e.key==='ArrowRight')col++;if(e.key==='ArrowUp')row--;if(e.key==='ArrowDown')row++;}else return;$(`[data-order-row="${row}"][data-order-col="${col}"]`)?.focus();});
$('#main').addEventListener('click',async e=>{const button=e.target.closest('button');if(!button)return;if(button.dataset.orderRemove!==undefined){orderDraft.rows.splice(Number(button.dataset.orderRemove),1);if(!orderDraft.rows.length)orderDraft.rows.push(newOrderRow());drawOrderEntry();return;}if(button.dataset.selectOrder){orderSelected=button.dataset.selectOrder;drawOrderReport();return;}const action=button.dataset.orderAction;if(!action)return;
 if(action==='save')saveOrder();
 if(action==='row'){orderDraft.rows.push(newOrderRow());drawOrderEntry();}
 if(action==='new'){if(orderDraft?.rows.some(row=>Object.values(row).some(v=>String(v).trim()))&&!confirm('Discard the current unsaved order entry?'))return;orderDraft={id:null,rows:Array.from({length:5},newOrderRow)};goPage('order-entry');}
 if(action==='clear'){orderSearch='';drawOrderReport();}
 if(action==='print')window.print();
 if(action==='edit'){if(activePage==='order-entry'&&!orderDraft.id){toast('This new file is already editable.');return;}if(orderSearch){const ids=[...new Set(filteredOrderRows().map(r=>r.fileId))];if(ids.length!==1){toast('Clear search and select one saved file to edit.');return;}editOrder(ids[0]);}else editOrder(activePage==='order-entry'?orderDraft.id:orderSelected);}
 if(action==='delete'){if(orderSearch){toast('Clear search and select the saved file to delete.');return;}const id=activePage==='order-entry'?orderDraft.id:orderSelected;if(!id){toast('Select a saved file first.');return;}const dialog=$('#deleteDialog');dialog.querySelector('h2').textContent='Delete this order file?';dialog.querySelector('p').textContent='All rows in this selected order file will be removed. Download a backup if you need a copy.';dialog.showModal();dialog.onclose=async ()=>{if(dialog.returnValue==='delete'){const next=structuredClone(state);preserveOrderNumbers(next.orderFiles);next.orderFiles=next.orderFiles.filter(f=>f.id!==id);if(await commit(next)){orderSelected=null;orderDraft=null;goPage('order-report');toast('Order file deleted');}}};}
 if(action==='excel'){try{let rows;if(activePage==='order-entry')rows=orderDraft.rows.filter(row=>Object.values(row).some(v=>String(v).trim()));else rows=orderSearch?filteredOrderRows():orderFiles().find(f=>f.id===orderSelected)?.rows||[];if(!rows.length){toast('No order rows to export.');return;}const matrix=[['SL',...orderColumns.map(([,label])=>label)],...rows.map((row,i)=>[i+1,...orderColumns.map(([key])=>key==='qty'?Number(String(row.qty).replaceAll(',','').replace(/[০-৯]/g,c=>'০১২৩৪৫৬৭৮৯'.indexOf(c))):key.endsWith('Date')&&row[key]?normalizeDate(row[key]):row[key])])];if(matrix.some(row=>row.some(cell=>typeof cell==='number'&&!Number.isFinite(cell))))throw Error('Enter a valid ORDER QTY before exporting.');download('order-report.xlsx',makeXlsx(matrix,'ORDER REPORT'),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');toast('Order Excel file downloaded');}catch(error){toast(error.message);}}
});
