'use strict';
const payrollCore=window.FarnoorPayrollCore,payrollPreviousRenderer=renderPage;
let payrollLegacy=false;let payrollScreen='salary',payrollShowOpen=false,payrollShowReport=false,payrollBusy=false;
const payrollDrafts=new Map();
const payrollToday=()=>new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Dhaka'}).format(new Date());
const payrollMoney=value=>Number(value||0).toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2});
const payrollPreviousFilteredRows=filteredRows;filteredRows=function(){const rows=payrollPreviousFilteredRows();return activePage==='payroll'&&payrollLegacy?rows.filter(r=>!r.payrollForm&&!r.hrSourceForm):rows;};
const payrollRecords=()=>state.records.payroll||[];
const payrollDateNumber=value=>{if(!value)return 0;const [d,m,y]=normalizeDate(value).split('/').map(Number);return y*10000+m*100+d;};
const payrollMonth=value=>{const [d,m,y]=normalizeDate(value).split('/');return y+'-'+m;};
function payrollNewDraft(kind){const form=payrollCore.formById(kind),values={};for(const field of form.fields){values[field.key]=field.value||'';if(field.type==='date')values[field.key]=field.key==='fromDate'?'01/'+payrollToday().slice(3):payrollToday();if(field.type==='checkbox')values[field.key]='false';}if(form.fields.some(f=>f.key==='index'))values.index=String(payrollRecords().filter(r=>r.payrollForm===kind).length+1);return {id:null,values,dirty:false,attendance:new Map()};}
function payrollDraft(){if(!payrollDrafts.has(payrollScreen))payrollDrafts.set(payrollScreen,payrollNewDraft(payrollScreen));return payrollDrafts.get(payrollScreen);}
function payrollOptions(field){if(window.FARNOOR_PAYROLL_OPTIONS?.[field.key])return window.FARNOOR_PAYROLL_OPTIONS[field.key];if(field.type==='department')return [...new Set(['Administration','Account','Commercial','Merchandising','Knitting and Dyeing','Store','Production','Cutting','Finishing','Packing','Quality','Sample','Maintenance','Electrical',...DEPARTMENTS.map(d=>d.name)])];if(field.type==='section')return window.FARNOOR_PAYROLL_SECTIONS||[];if(field.type==='designation')return window.FARNOOR_PAYROLL_DESIGNATIONS||[];return field.options||[];}
function payrollField(field,values,scope='entry'){
 const value=values[field.key]??field.value??'',id='pr-'+scope+'-'+field.key,disabled=scope==='rules'?(!pagePermission('edit')?'disabled':''):(!payrollCore.formById(payrollScreen).report&&!pagePermission('edit')?'disabled':'');
 let input;
 if(['select','department','section','designation'].includes(field.type)||window.FARNOOR_PAYROLL_OPTIONS?.[field.key]){const options=[...new Set([...payrollOptions(field),...(value?[value]:[])])];input=`<select id="${id}" data-payroll-field="${field.key}" data-payroll-scope="${scope}" ${disabled}><option value=""></option>${options.map(v=>`<option ${v===value?'selected':''}>${esc(v)}</option>`).join('')}</select>`;}
 else if(field.type==='checkbox')input=`<input type="checkbox" id="${id}" data-payroll-field="${field.key}" data-payroll-scope="${scope}" ${value==='true'?'checked':''}>`;
 else input=`<input id="${id}" data-payroll-field="${field.key}" data-payroll-scope="${scope}" type="${field.type==='month'?'month':field.type==='number'?'number':'text'}" ${field.type==='number'?'min="0" max="1000000000" step="0.01"':''} maxlength="500" ${field.type==='date'?'placeholder="1/1/26"':''} value="${esc(value)}" ${disabled}>`;
 return `<tr><td><label for="${id}">${esc(field.label)}</label></td><td><div class="payroll-field">${input}<button type="button" data-payroll-clear="${field.key}" data-payroll-scope="${scope}" ${disabled}>Clear</button></div></td></tr>`;
}
function payrollTable(fields,values,scope='entry'){return `<table class="payroll-form-table"><tbody>${fields.map(f=>payrollField(f,values,scope)).join('')}</tbody></table>`;}
renderPage=function(){if(activePage!=='payroll'){payrollPreviousRenderer();return;}if(payrollLegacy){payrollPreviousRenderer();$('#main').insertAdjacentHTML('afterbegin','<button type="button" data-payroll-action="back">Back to Payroll</button>');return;}renderPayroll();};
function renderPayroll(){
 const form=payrollCore.formById(payrollScreen),draft=payrollDraft(),rules=payrollRecords().find(r=>r.payrollForm==='rules')?.payrollValues||{};
 $('#main').innerHTML=heading('HR','Payroll','')+`<div class="payroll-workspace"><nav class="payroll-menu no-print" aria-label="Payroll menus">${payrollCore.forms.map(f=>`<button type="button" data-payroll-menu="${f.id}" class="${f.id===payrollScreen?'selected':''}" aria-expanded="${f.id===payrollScreen}"><span>${f.icon}</span>${esc(f.name)}<span>${f.id===payrollScreen?'−':'+'}</span></button>`).join('')}${payrollRecords().some(r=>!r.payrollForm&&!r.hrSourceForm)?'<button type="button" data-payroll-action="legacy">Existing Payroll records</button>':''}</nav><div class="payroll-content">${draft.collapsed?'':`<section class="payroll-paper"><h3 class="payroll-title">${esc(form.title)}</h3><div class="payroll-entry no-print">${payrollTable(form.fields,draft.values)}${payrollScreen==='salary'?`<details class="payroll-details"><summary>Employee details</summary>${payrollTable(payrollCore.metadata,draft.values)}</details>`:''}<div class="payroll-controls">${form.report?'<button type="button" data-payroll-action="search">Search</button>':'<button type="button" data-payroll-action="open">Open</button><button type="button" class="primary" data-payroll-action="save" data-page-action-required="edit">Save</button>'}<button type="button" data-payroll-action="clear">Clear</button><button type="button" data-payroll-action="new">New</button></div>${draft.dirty?'<p class="hint">Unsaved changes</p>':''}</div>${payrollScreen==='generator'?`<details class="payroll-details no-print"><summary>Company salary calculation rules</summary><p class="hint">Enter your company’s approved calculation rules before generating salaries.</p>${payrollTable(payrollCore.rules,rules,'rules')}<div class="payroll-controls"><button type="button" data-payroll-action="save-rules" data-page-action-required="edit">Save Rules</button></div></details><div class="payroll-controls no-print"><button type="button" data-payroll-action="attendance">Attendance / Deductions</button><button type="button" data-payroll-action="generate" data-page-action-required="edit">Generate & Save Salary</button></div>`:''}${payrollScreen==='adjustment'?'<div class="payroll-controls no-print"><button type="button" data-payroll-action="attendance">Edit OT Adjustment</button></div>':''}${draft.showAttendance?payrollAttendanceTable():''}${payrollShowOpen&&!form.report?payrollOpenTable():''}${payrollShowReport&&form.report?payrollReport():''}</section>`}</div></div>`;
 $('#main').querySelectorAll('[data-page-action-required="edit"]').forEach(b=>b.disabled=payrollBusy||!pagePermission('edit'));
}
function payrollEmployeeRows(){const date=payrollDraft().values.date||payrollToday(),latest=new Map();for(const row of payrollRecords().filter(r=>r.payrollForm==='salary'&&payrollDateNumber(r.date)<=payrollDateNumber(date)).sort((a,b)=>payrollDateNumber(a.date)-payrollDateNumber(b.date)))latest.set(row.payrollValues.empId,row.payrollValues);return [...latest.values()].filter(v=>v.profileStatus==='Active'&&payrollMatches(v,payrollDraft().values,false));}
function payrollMatches(v,filters,useDate=true){for(const key of ['empId','branch','empGroup','department','section','designation','paymentGroup','floor','workingSection','sectionGroup','desigGroup','workGroup','workShift'])if(filters[key]&&filters[key]!=='All Shift'&&String(v[key]||'').toLowerCase()!==String(filters[key]).toLowerCase())return false;if(filters.profileStatus&&v.profileStatus&&v.profileStatus!==filters.profileStatus)return false;if(useDate&&filters.dateRange==='true'){const d=payrollDateNumber(v.date||v.period&&('01/'+v.period.slice(5)+'/'+v.period.slice(0,4)));if(d<payrollDateNumber(filters.fromDate)||d>payrollDateNumber(filters.toDate))return false;}return true;}
function payrollOpenTable(){const form=payrollCore.formById(payrollScreen),rows=payrollRecords().filter(r=>r.payrollForm===payrollScreen);return `<div class="payroll-open-list table-wrap"><table class="payroll-result"><thead><tr><th>Index</th><th>Emp ID</th><th>Name</th><th>Date</th><th>Amount</th><th>Status</th><th class="no-print">Open</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.payrollValues.empId||'')}</td><td>${esc(r.name)}</td><td>${esc(r.date)}</td><td>${payrollMoney(r.quantity)}</td><td>${esc(r.payrollValues.profileStatus||'')}</td><td class="no-print"><button type="button" data-payroll-open="${esc(r.id)}">Open</button><button type="button" data-payroll-delete="${esc(r.id)}" data-page-action-required="edit">Delete</button></td></tr>`).join('')||'<tr><td colspan="7" class="payroll-empty">No saved records.</td></tr>'}</tbody></table></div>`;}
function payrollAttendanceTable(){const draft=payrollDraft(),period=payrollMonth(draft.values.date||payrollToday()),employees=payrollEmployeeRows();for(const e of employees)if(!draft.attendance.has(e.empId)){const saved=payrollRecords().find(r=>r.payrollForm==='attendance'&&r.payrollValues.empId===e.empId&&r.payrollValues.period===period);draft.attendance.set(e.empId,{empId:e.empId,empName:e.empName,period,...saved?.payrollValues});}const fields=payrollCore.attendance.filter(f=>!['empId','empName','period'].includes(f.key));return `<div class="payroll-result no-print"><h3 class="payroll-subheading">Attendance / Deductions · ${esc(period)}</h3><div class="table-wrap"><table class="payroll-attendance"><thead><tr><th>Emp ID</th><th>Name</th>${fields.map(f=>`<th>${esc(f.label)}</th>`).join('')}</tr></thead><tbody>${employees.map(e=>`<tr><td>${esc(e.empId)}</td><td>${esc(e.empName)}</td>${fields.map(f=>`<td><input type="number" min="0" max="1000000000" step="0.01" aria-label="${esc(e.empId+' '+f.label)}" data-payroll-attendance="${esc(e.empId)}" data-payroll-key="${f.key}" value="${esc(draft.attendance.get(e.empId)[f.key]??'')}" ${!pagePermission('edit')?'disabled':''}></td>`).join('')}</tr>`).join('')||'<tr><td colspan="16">Add Employee Salary records first.</td></tr>'}</tbody></table></div><div class="payroll-controls"><button type="button" data-payroll-action="save-attendance" data-page-action-required="edit">Save Attendance / Deductions</button></div></div>`;}
function payrollRecord(type,values,id){const normalized={...values};for(const f of [...(payrollCore.formById(type)?.fields||[]),...payrollCore.metadata])if(f.type==='date'&&normalized[f.key])normalized[f.key]=normalizeDate(normalized[f.key]);payrollCore.checkValues(type,normalized);const date=normalized.date||normalized.period&&('01/'+normalized.period.slice(5)+'/'+normalized.period.slice(0,4))||payrollToday();return {id:id||crypto.randomUUID(),reference:String(normalized.empId||normalized.index||type),name:String(normalized.empName||payrollCore.formById(type)?.name||type),quantity:Math.max(0,Number(normalized.gross||normalized.amount||normalized.net||normalized.NetPayableAmount||0)),date,status:'Completed',payrollForm:type,payrollValues:normalized};}
async function payrollSaveRows(rows,replaceIds=[]){if(!pagePermission('edit'))throw Error('EDIT permission is required.');const next=structuredClone(state),ids=new Set(replaceIds);next.records.payroll=[...payrollRecords().filter(r=>!ids.has(r.id)),...rows];payrollBusy=true;try{if(!await commit(next))return false;toast('Payroll saved online.');return true;}finally{payrollBusy=false;}}
function payrollLatestPolicy(type,employee,date){return payrollRecords().filter(r=>r.payrollForm===type&&r.payrollValues.profileStatus!=='Inactive'&&payrollDateNumber(r.date)<=payrollDateNumber(date)&&(!r.payrollValues.empId||r.payrollValues.empId===employee.empId)&&(!r.payrollValues.designation||r.payrollValues.designation===employee.designation)&&(!r.payrollValues.section||r.payrollValues.section===employee.section)&&(!r.payrollValues.empGroup||r.payrollValues.empGroup===employee.empGroup)).sort((a,b)=>(!!b.payrollValues.empId-!!a.payrollValues.empId)||payrollDateNumber(b.date)-payrollDateNumber(a.date))[0]?.payrollValues;}
async function payrollGenerate(){
 const draft=payrollDraft(),date=normalizeDate(draft.values.date),period=payrollMonth(date),rule=payrollRecords().find(r=>r.payrollForm==='rules')?.payrollValues||{},employees=payrollEmployeeRows();if(!employees.length)throw Error('No Employee Salary records match these filters.');
 const rows=[];for(const salary of employees){const a=payrollRecords().find(r=>r.payrollForm==='attendance'&&r.payrollValues.empId===salary.empId&&r.payrollValues.period===period)?.payrollValues;if(!a)throw Error('Save attendance for '+salary.empId+' before generating salaries.');for(const key of ['present','absent','leave','holiday'])if(a[key]===''||a[key]===undefined)throw Error('Enter all attendance day totals for '+salary.empId+'.');
  const ot=payrollLatestPolicy('ot-policy',salary,date),att=payrollLatestPolicy('att-policy',salary,date),increments=payrollRecords().filter(r=>r.payrollForm==='increment'&&r.payrollValues.empId===salary.empId&&r.payrollValues.profileStatus==='Active'&&payrollDateNumber(r.date)>payrollDateNumber(salary.date)&&payrollDateNumber(r.date)<=payrollDateNumber(date));
  const bonuses=payrollRecords().filter(r=>r.payrollForm==='bonus'&&r.payrollValues.empId===salary.empId&&r.payrollValues.profileStatus==='Active'&&payrollMonth(r.date)===period);
  const loans=payrollRecords().filter(r=>r.payrollForm==='loan'&&r.payrollValues.empId===salary.empId&&r.payrollValues.profileStatus==='Active').filter(r=>{const [y,m]=period.split('-').map(Number),[sy,sm]=payrollMonth(r.date).split('-').map(Number),elapsed=(y-sy)*12+m-sm;return elapsed>=0&&elapsed<Number(r.payrollValues.duration);});
  const calculated=payrollCore.calculate(salary,a,rule,{...(ot?.otRate?{otRate:ot.otRate}:{}),fixedAmount:ot?.fixedAmount||0,increment:increments.reduce((s,r)=>s+Number(r.payrollValues.amount),0),attendanceBonus:Number(a.absent)===0?att?.amount||0:0,bonus:bonuses.reduce((s,r)=>s+Number(r.payrollValues.amount),0),advanceDeduction:loans.reduce((s,r)=>s+Number(r.payrollValues.amount)/Number(r.payrollValues.duration),0)});
  const values=Object.fromEntries(payrollCore.generatedFields.filter(k=>calculated[k]!==undefined).map(k=>[k,String(calculated[k])]));rows.push({...payrollRecord('generated',values),date});
 }
 const replace=payrollRecords().filter(r=>r.payrollForm==='generated'&&r.payrollValues.period===period&&employees.some(e=>e.empId===r.payrollValues.empId)).map(r=>r.id);
 if(replace.length&&!confirm('Replace the generated salary for '+period+' for these '+employees.length+' employees?'))return;
 if(await payrollSaveRows(rows,replace)){payrollShowReport=true;renderPayroll();}
}
function payrollReport(){
 const draft=payrollDraft(),v=draft.values,form=payrollCore.formById(payrollScreen),period=payrollMonth(v.date||v.fromDate||payrollToday());let data=[];
 if(payrollScreen==='increment-report')data=payrollRecords().filter(r=>r.payrollForm==='increment').map(r=>({...r.payrollValues,date:r.date}));
 else if(payrollScreen==='bonus-sheet'&&v.bonusType==='Entry Bonus')data=payrollRecords().filter(r=>r.payrollForm==='bonus').map(r=>({...r.payrollValues,date:r.date}));
 else data=payrollRecords().filter(r=>r.payrollForm==='generated'&&(v.dateRange==='true'||r.payrollValues.period===period)).map(r=>({...r.payrollValues,date:r.date}));
 data=data.map(r=>{const employee=payrollRecords().filter(x=>x.payrollForm==='salary'&&x.payrollValues.empId===r.empId).sort((a,b)=>payrollDateNumber(b.date)-payrollDateNumber(a.date))[0]?.payrollValues||{};return {...employee,...r,empName:r.empName||employee.empName||''};});data=data.filter(r=>payrollMatches(r,v));if(payrollScreen==='sheet'&&v.reportType==='Monthly Staff Salary')data=data.filter(r=>r.empGroup==='Staff');if(payrollScreen==='sheet'&&v.genStatus==='Resigned Employee')data=data.filter(r=>r.profileStatus==='Inactive');if(payrollScreen==='earned'&&v.joinMonth&&v.condition)data=data.filter(r=>{const joined=r.joinDate?payrollMonth(r.joinDate):'';return joined&&(v.condition==='='?joined===v.joinMonth:v.condition==='<='?joined<=v.joinMonth:joined>=v.joinMonth);});
 const meta=`<div class="payroll-report-meta"><h3>FARNOOR GARMENTS LTD.</h3><p>1028/1/2 MALIBAGH BAZAR ROAD, DHAKA-1217</p><h3>${esc(v.reportTitle||form.title)}</h3><p>Period: ${esc(period)} · Print Date: ${esc(v.printDate||payrollToday())}</p></div>`;
 if(payrollScreen==='slip')return `<div class="payroll-result">${meta}<div class="payroll-slips">${data.map(r=>`<article class="payroll-slip"><h4>${esc(r.empName)} · ${esc(r.empId)}</h4><p>${esc(r.department||'')} / ${esc(r.designation||'')} · ${esc(r.period)}</p><table><tbody>${[['gross','Gross Salary'],['basic','Basic'],['houseRent','House Rent'],['medical','Medical'],['transport','Transport'],['food','Fooding'],['otAmount','Overtime'],['attendanceBonus','Attn Bonus'],['bonus','Bonus'],['absenceDeduction','Absent Deduction'],['advanceDeduction','Loan / Advance'],['ait','AIT'],['pf','PF'],['stamp','Stamp'],['net','Net Payable']].map(([k,l])=>`<tr><td>${l}</td><td>${payrollMoney(r[k])}</td></tr>`).join('')}</tbody></table><div class="payroll-signatures"><span>Prepared by</span><span>Received by</span></div></article>`).join('')||'<p class="payroll-empty">No generated salary for this period.</p>'}</div></div>`;
 let columns;
 if(payrollScreen==='increment-report')columns=[['empId','Emp ID'],['empName','Name'],['date','Effective Date'],['amount','Increment','money']];
 else if(payrollScreen==='bonus-sheet'){data=data.map(r=>({...r,amount:v.bonusType==='Entry Bonus'?r.amount:String(payrollCore.round(Number(r[v.bonusOn==='Gross'?'gross':'basic']||0)*Number(v.percentage||0)/100))}));columns=[['empId','Emp ID'],['empName','Name'],['department','Department'],['basic','Basic','money'],['gross','Gross','money'],['amount','Bonus','money']];}
 else if(payrollScreen==='earned'){const rule=payrollRecords().find(r=>r.payrollForm==='rules')?.payrollValues;if(!rule?.earnedDivisor)throw Error('Set the Earn Leave Daily Divisor in Company salary calculation rules.');data=data.map(r=>({...r,earnedAmount:String(payrollCore.round(Number(r.earnedDays||0)*Number(r[v.calcOn==='Gross'?'gross':'basic']||0)/Number(rule.earnedDivisor)*Number(v.percentage||0)/100))}));columns=[['empId','Emp ID'],['empName','Name'],['joinDate','Date of Join'],['earnedDays','Earn Leave Days'],['earnedAmount','Amount','money']];}
 else if(payrollScreen==='adjustment'||payrollScreen==='sheet'&&v.reportType==='Overtime Sheet')columns=[['empId','Emp ID'],['empName','Name'],['department','Department'],['otHours','OT Hours'],['otRate','OT Rate','money'],['otAmount','OT Amount','money']];
 else if(payrollScreen==='sheet'&&v.reportType==='Night and Dinner Bill')columns=[['empId','Emp ID'],['empName','Name'],['department','Department'],['night','Night Allowance','money']];
 else if(payrollScreen==='sheet'&&v.reportType==='Top Sheet Wages'){const grouped=new Map();for(const row of data){const key=row.department||'Unassigned';if(!grouped.has(key))grouped.set(key,{department:key,employees:0,gross:0,otAmount:0,net:0});const total=grouped.get(key);total.employees++;for(const amount of ['gross','otAmount','net'])total[amount]+=Number(row[amount]||0);}data=[...grouped.values()];columns=[['department','Department'],['employees','Employees'],['gross','Gross','money'],['otAmount','OT','money'],['net','Net Payable','money']];}
 else columns=[['empId','Emp ID'],['empName','Name'],['department','Department'],['gross','Gross','money'],['basic','Basic','money'],['houseRent','House Rent','money'],['medical','Medical','money'],['transport','Transport','money'],['food','Fooding','money'],['present','Present'],['absent','Absent'],['otHours','OT Hours'],['otAmount','OT Amount','money'],['attendanceBonus','Attn Bonus','money'],['bonus','Bonus','money'],['absenceDeduction','Absent Deduction','money'],['advanceDeduction','Advance Ded','money'],['ait','AIT','money'],['pf','PF','money'],['stamp','Stamp','money'],['net','Net Payable','money']];
 draft.reportData=data;draft.reportColumns=columns;
 return `<div class="payroll-result">${meta}<div class="payroll-controls no-print"><button type="button" data-payroll-action="csv">Export CSV</button><button type="button" data-payroll-action="xlsx">Export Excel</button></div><div class="table-wrap"><table><thead><tr><th>SL</th>${columns.map(c=>`<th>${esc(c[1])}</th>`).join('')}</tr></thead><tbody>${data.map((r,i)=>`<tr><td>${i+1}</td>${columns.map(c=>`<td>${c[2]==='money'?payrollMoney(r[c[0]]):esc(r[c[0]]||'')}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${columns.length+1}" class="payroll-empty">No saved records match this period and these filters.</td></tr>`}</tbody>${data.length?`<tfoot><tr class="payroll-total"><td>Total</td>${columns.map(c=>`<td>${c[2]==='money'?payrollMoney(data.reduce((s,r)=>s+Number(r[c[0]]||0),0)):''}</td>`).join('')}</tr></tfoot>`:''}</table></div><div class="payroll-signatures"><span>Prepared by</span><span>Checked by</span><span>Approved by</span></div></div>`;
}
$('#main').addEventListener('input',event=>{if(activePage!=='payroll')return;const t=event.target,draft=payrollDraft();if(t.dataset.payrollAttendance){draft.attendance.get(t.dataset.payrollAttendance)[t.dataset.payrollKey]=t.value;draft.dirty=true;}else if(t.dataset.payrollField&&t.dataset.payrollScope==='entry'){draft.values[t.dataset.payrollField]=t.type==='checkbox'?String(t.checked):t.value;draft.dirty=true;}});
$('#main').addEventListener('change',event=>{if(activePage!=='payroll')return;const t=event.target;if(t.dataset.payrollField&&t.dataset.payrollScope==='entry'){const draft=payrollDraft();draft.values[t.dataset.payrollField]=t.type==='checkbox'?String(t.checked):t.value;draft.dirty=true;}});
document.addEventListener('click',async event=>{
 if(activePage!=='payroll'||payrollBusy)return;const button=event.target.closest('button');if(!button)return;
 try{
  if(button.dataset.payrollAction==='legacy'){payrollLegacy=true;renderPage();return;}if(button.dataset.payrollAction==='back'){payrollLegacy=false;renderPage();return;}if(button.dataset.payrollMenu){const id=button.dataset.payrollMenu;if(id===payrollScreen)payrollDraft().collapsed=!payrollDraft().collapsed;else{payrollScreen=id;payrollDraft().collapsed=false;payrollShowOpen=false;payrollShowReport=false;}renderPayroll();return;}
  if(button.dataset.payrollClear){const input=$('#pr-'+button.dataset.payrollScope+'-'+button.dataset.payrollClear);input.value='';if(input.type==='checkbox')input.checked=false;if(button.dataset.payrollScope==='entry'){payrollDraft().values[button.dataset.payrollClear]='';payrollDraft().dirty=true;}return;}
  if(button.dataset.payrollOpen){const r=payrollRecords().find(r=>r.id===button.dataset.payrollOpen);payrollDrafts.set(payrollScreen,{id:r.id,values:{...r.payrollValues},dirty:false,attendance:new Map()});payrollShowOpen=false;renderPayroll();return;}
  if(button.dataset.payrollDelete){if(!pagePermission('edit'))throw Error('EDIT permission is required.');if(confirm('Delete this Payroll record?')){await payrollSaveRows([], [button.dataset.payrollDelete]);renderPayroll();}return;}
  const action=button.dataset.payrollAction;if(!action)return;const draft=payrollDraft(),form=payrollCore.formById(payrollScreen);
  if(['save','save-rules','save-attendance','generate'].includes(action)&&!pagePermission('edit'))throw Error('EDIT permission is required.');
  if(action==='open'){payrollShowOpen=!payrollShowOpen;renderPayroll();}
  if(action==='new'||action==='clear'){if(draft.dirty&&!confirm('Clear the unsaved Payroll inputs?'))return;payrollDrafts.set(payrollScreen,payrollNewDraft(payrollScreen));payrollShowOpen=false;payrollShowReport=false;renderPayroll();}
  if(action==='save'){const r=payrollRecord(payrollScreen,draft.values,draft.id);if(await payrollSaveRows([r],draft.id?[draft.id]:[])){draft.id=r.id;draft.values=r.payrollValues;draft.dirty=false;renderPayroll();}}
  if(action==='search'){for(const f of form.fields)if(f.type==='date'&&draft.values[f.key])draft.values[f.key]=normalizeDate(draft.values[f.key]);if(draft.values.dateRange==='true'&&payrollDateNumber(draft.values.fromDate)>payrollDateNumber(draft.values.toDate))throw Error('Date From must be before Date To.');payrollShowReport=true;renderPayroll();}
  if(action==='attendance'){draft.showAttendance=!draft.showAttendance;renderPayroll();}
  if(action==='save-attendance'){const values=[...draft.attendance.values()];if(!values.length)throw Error('No employee attendance to save.');const rows=values.map(v=>payrollRecord('attendance',v)),ids=payrollRecords().filter(r=>r.payrollForm==='attendance'&&values.some(v=>v.empId===r.payrollValues.empId&&v.period===r.payrollValues.period)).map(r=>r.id);if(await payrollSaveRows(rows,ids)){draft.dirty=false;renderPayroll();}}
  if(action==='save-rules'){const values={};$('#main').querySelectorAll('[data-payroll-scope="rules"][data-payroll-field]').forEach(input=>values[input.dataset.payrollField]=input.value);for(const field of payrollCore.rules)if(values[field.key]==='')throw Error('Enter '+field.label+'.');const old=payrollRecords().filter(r=>r.payrollForm==='rules');if(await payrollSaveRows([payrollRecord('rules',values)],old.map(r=>r.id)))renderPayroll();}
  if(action==='generate')await payrollGenerate();
  if(action==='csv'){const cols=draft.reportColumns||[],rows=draft.reportData||[],quote=v=>'"'+String(v??'').replace(/"/g,'""')+'"';download('farnoor-'+payrollScreen+'.csv','\ufeff'+[cols.map(c=>quote(c[1])).join(','),...rows.map(r=>cols.map(c=>quote(r[c[0]])).join(','))].join('\r\n'),'text/csv');}
  if(action==='xlsx'){const cols=draft.reportColumns||[],rows=draft.reportData||[];download('farnoor-'+payrollScreen+'.xlsx',makeXlsx([cols.map(c=>c[1]),...rows.map(r=>cols.map(c=>c[2]==='money'?Number(r[c[0]]||0):r[c[0]]||''))], 'PAYROLL'),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');}
 }catch(error){toast(error.message);}
});
