'use strict';
let adminView=false,accessInfo={role:'member',department:'',pages:[],revision:0},adminData=null,selectedDepartment='Admin',departmentPanelOpen=false,adminLoading=false;
let adminUserPanel='';
const adminUserLists={users:null,running:null},adminUserLoading={users:false,running:false},adminUserErrors={users:'',running:''};
const permissionDrafts=new Map();
const PAGE_ACTIONS=['edit','view','pdf','print'];
function canAction(id,action){return accessInfo.role==='super_admin'||(accessInfo.actions?accessInfo.actions[id]?.includes(action):accessInfo.pages.includes(id))||false;}
function canPage(id){return canAction(id,'view');}
function applyPageLinks(){document.querySelectorAll('[data-open-page]').forEach(node=>{node.hidden=!canPage(node.dataset.openPage);});}
function applyAccess(access){const changed=JSON.stringify(accessInfo)!==JSON.stringify(access);accessInfo=access||{role:'member',department:'',pages:[],revision:0};$('#superAdminButton').hidden=accessInfo.role!=='super_admin';$('#profileRole').textContent=accessInfo.role==='super_admin'?'Super Admin':accessInfo.department||'Member';$('#restoreButton').hidden=accessInfo.role!=='super_admin';if(activePage&&!canPage(activePage)){activePage=null;document.querySelectorAll('dialog[open]').forEach(dialog=>dialog.close());toast('Your page permissions changed.');}if(accessInfo.role!=='super_admin')adminView=false;renderNavigation();applyPageLinks();return changed;}
window.FarnoorAccess={canPage,canAction,apply:applyAccess};
const authorizedGoPage=goPage;goPage=function(id){if(!canPage(id)){toast('This page has not been permitted for your department.');return;}adminView=false;authorizedGoPage(id);applyPageLinks();};
const authorizedRenderPage=renderPage;renderPage=function(){if(!activePage||!canPage(activePage)){activePage=null;renderOverview();return;}authorizedRenderPage();applyPageLinks();};
const authorizedOverview=renderOverview;renderOverview=function(){adminView=false;if(accessInfo.role!=='super_admin'&&!accessInfo.pages.length){activePage=null;renderNavigation();$('#main').innerHTML=heading('DEPARTMENT ACCESS','Permission pending','Your Super Admin can tick the pages permitted for your department.')+`<section class="panel access-empty"><h3>${esc(accessInfo.department||'Your department')}</h3><p>No pages have been permitted yet. Contact your Super Admin.</p></section>`;return;}authorizedOverview();applyPageLinks();};
async function adminRequest(route,options={}){const response=await FarnoorAPI.request('/api/admin/'+route,{...options,headers:{'Content-Type':'application/json'}});const body=await response.json();if(!response.ok)throw Object.assign(Error(body.error||'Could not load permissions.'),{status:response.status});return body;}
async function loadAdministration(){if(adminLoading)return;adminLoading=true;try{adminData=await adminRequest('departments');if(adminView)renderAdminView();}catch(error){toast(error.message);if(adminView)$('#adminLoadMessage').textContent=error.message;}finally{adminLoading=false;}}
function draftFor(department){if(!permissionDrafts.has(department)){const saved=adminData.permissions.find(p=>p.department===department);permissionDrafts.set(department,{pages:new Set(saved?.pages||[]),actions:Object.fromEntries(window.FARNOOR_PAGE_CATALOG.map(page=>[page.id,new Set(saved?.actions?.[page.id]||(saved?.pages?.includes(page.id)?PAGE_ACTIONS:[]))])),revision:saved?.revision||0,saving:false,dirty:false});}return permissionDrafts.get(department);}
function renderAdminView(){if(accessInfo.role!=='super_admin'){adminView=false;renderOverview();return;}activePage=null;renderNavigation();$('#main').innerHTML=heading('SUPER ADMIN','Super Admin','Manage department access to every subdepartment and page.')+`<div class="admin-section-buttons"><button id="adminDepartments" class="admin-department-button" aria-expanded="${departmentPanelOpen}">▦ Department <span>${departmentPanelOpen?'−':'+'}</span></button><button id="adminUserList" class="admin-department-button admin-users-button" aria-expanded="${adminUserPanel==='users'}">♙ User List <span>${adminUserPanel==='users'?'−':'+'}</span></button><button id="adminRunningUsers" class="admin-department-button admin-running-button" aria-expanded="${adminUserPanel==='running'}">● Running Users <span>${adminUserPanel==='running'?'−':'+'}</span></button></div><div id="adminLoadMessage" role="status">${adminData?'':'Loading departments…'}</div>`;if(adminUserPanel){renderAdminUsers();return;}if(!departmentPanelOpen||!adminData)return;const draft=draftFor(selectedDepartment),users=adminData.users.filter(u=>u.department===selectedDepartment),catalog=window.FARNOOR_PAGE_CATALOG;
const moduleNames={hr:'Administration',accounts:'Account'};
const orderedModules=[...DEPARTMENTS.filter(m=>!['admin','sewing'].includes(m.id)),...DEPARTMENTS.filter(m=>['admin','sewing'].includes(m.id))];
function actionBoxes(page){return `<span class="permission-action-boxes">${PAGE_ACTIONS.map(action=>`<label class="permission-action-cell"><input type="checkbox" data-permission-page="${page.id}" data-permission-action="${action}" aria-label="${action.toUpperCase()} ${esc(page.parent?page.parent+' / ':'')}${esc(page.name)}" ${draft.actions[page.id].has(action)?'checked':''}></label>`).join('')}</span>`;}
function pageRow(page){page={...DEPARTMENTS.flatMap(module=>module.pages).find(item=>item.id===page.id),...page};return `<div class="permission-page" style="--page-shade:${page.shade||'#f3f7ef'}"><span class="permission-page-name"><span class="permission-page-icon">${esc(page.icon||'▤')}</span>${esc(page.name)}${page.hidden?' (Legacy)':''}</span>${actionBoxes(page)}</div>`;}
$('#main').insertAdjacentHTML('beforeend',`<section class="permission-layout"><div class="panel permission-editor"><div class="department-dropdown"><label for="permissionDepartment">Department</label><select id="permissionDepartment">${adminData.groups.map(group=>`<optgroup label="${esc(group.name)}">${group.departments.map(name=>`<option value="${esc(name)}" ${name===selectedDepartment?'selected':''}>${esc(name)}</option>`).join('')}</optgroup>`).join('')}</select></div><div class="permission-controls"><button type="button" id="permitAll">Tick all</button><button type="button" id="permitNone">Untick all</button><button type="button" id="reloadPermissions">Reload permissions</button></div><div class="permission-column-head"><span>Departments, subdepartments and pages</span><span class="permission-action-head">${['Edit','View','Pdf','Print'].map(label=>`<span>${label}</span>`).join('')}</span></div><div class="permission-module-list">${orderedModules.map(module=>{const pages=catalog.filter(p=>p.moduleId===module.id),checked=pages.every(p=>draft.pages.has(p.id)),moduleName=moduleNames[module.id]||module.name,parents=[...new Set(pages.map(p=>p.parent).filter(Boolean))];return `<details class="permission-module" open><summary><span class="permission-module-name"><span class="permission-icon" style="background:${module.color}">${module.icon}</span>${esc(moduleName)}</span><small>${pages.filter(p=>draft.pages.has(p.id)).length}/${pages.length}</small><span class="permission-action-boxes">${PAGE_ACTIONS.map(action=>`<label class="permission-action-cell"><input type="checkbox" data-permission-module="${module.id}" data-permission-action="${action}" aria-label="All ${esc(moduleName)} ${action.toUpperCase()}" ${pages.every(page=>draft.actions[page.id].has(action))?'checked':''}></label>`).join('')}</span></summary><div>${pages.filter(p=>!p.parent).map(pageRow).join('')}${parents.map(parent=>`<details class="permission-subdepartment" open><summary>${esc(parent)}</summary><div>${pages.filter(p=>p.parent===parent).map(pageRow).join('')}</div></details>`).join('')}</div></details>`;}).join('')}</div><div class="permission-save"><span id="permissionSaveStatus" role="status">${draft.dirty?'Unsaved changes':'Saved permissions'}</span><button type="button" class="primary" id="savePermissions" ${draft.saving?'disabled':''}>${draft.saving?'Saving…':'Save Permissions'}</button></div></div></section>`);
document.querySelectorAll('[data-permission-module]').forEach(input=>{const pages=catalog.filter(p=>p.moduleId===input.dataset.permissionModule),count=pages.filter(p=>draft.actions[p.id].has(input.dataset.permissionAction)).length;input.indeterminate=count>0&&count<pages.length;});}
$('#superAdminButton').onclick=()=>{adminView=!adminView;if(!adminView){renderOverview();return;}activePage=null;renderAdminView();loadAdministration();};
$('#main').addEventListener('click',async event=>{if(!adminView)return;const button=event.target.closest('button');if(!button)return;if(button.id==='adminDepartments'){departmentPanelOpen=!departmentPanelOpen;adminUserPanel='';renderAdminView();if(!adminData)loadAdministration();}if(button.id==='adminUserList'||button.id==='adminRunningUsers'){const kind=button.id==='adminUserList'?'users':'running';adminUserPanel=adminUserPanel===kind?'':kind;departmentPanelOpen=false;renderAdminView();if(adminUserPanel)loadAdminUsers(kind);}if(button.id==='refreshAdminUsers'&&adminUserPanel)loadAdminUsers(adminUserPanel);if(button.dataset.permissionDepartment){selectedDepartment=button.dataset.permissionDepartment;renderAdminView();}if(button.id==='permitAll'||button.id==='permitNone'){const draft=draftFor(selectedDepartment);if(draft.saving)return;draft.pages=new Set(button.id==='permitAll'?window.FARNOOR_PAGE_CATALOG.map(p=>p.id):[]);for(const page of window.FARNOOR_PAGE_CATALOG)draft.actions[page.id]=new Set(button.id==='permitAll'?PAGE_ACTIONS:[]);draft.dirty=true;renderAdminView();}if(button.id==='reloadPermissions'){const draft=draftFor(selectedDepartment);if(draft.saving)return;if(draft.dirty&&!confirm('Discard unsaved permission changes for this department?'))return;permissionDrafts.delete(selectedDepartment);await loadAdministration();}if(button.id==='savePermissions'){const department=selectedDepartment,draft=draftFor(department);if(draft.saving)return;draft.saving=true;renderAdminView();try{const result=await adminRequest('permissions',{method:'POST',body:JSON.stringify({department,pages:[...draft.pages],actions:Object.fromEntries(Object.entries(draft.actions).map(([id,rights])=>[id,[...rights]])),revision:draft.revision})});draft.revision=result.revision;draft.dirty=false;const saved=adminData.permissions.find(p=>p.department===department);Object.assign(saved,result);toast('Department permissions saved.');}catch(error){toast(error.message);}finally{draft.saving=false;if(adminView)renderAdminView();}}});
function changeAction(draft,id,action,checked){const rights=draft.actions[id];if(checked){rights.add(action);if(action!=='view')rights.add('view');}else if(action==='view')rights.clear();else rights.delete(action);if(rights.has('view'))draft.pages.add(id);else draft.pages.delete(id);}
$('#main').addEventListener('change',event=>{if(!adminView||!adminData)return;const target=event.target;if(target.id==='permissionDepartment'){selectedDepartment=target.value;renderAdminView();return;}const draft=draftFor(selectedDepartment);if(draft.saving)return;if(target.dataset.permissionPage)changeAction(draft,target.dataset.permissionPage,target.dataset.permissionAction,target.checked);else if(target.dataset.permissionModule){for(const page of window.FARNOOR_PAGE_CATALOG.filter(p=>p.moduleId===target.dataset.permissionModule))changeAction(draft,page.id,target.dataset.permissionAction,target.checked);}else return;draft.dirty=true;$('#permissionSaveStatus').textContent='Unsaved changes';document.querySelectorAll('[data-permission-module]').forEach(input=>{const pages=window.FARNOOR_PAGE_CATALOG.filter(p=>p.moduleId===input.dataset.permissionModule),count=pages.filter(p=>draft.actions[p.id].has(input.dataset.permissionAction)).length;input.checked=count===pages.length;input.indeterminate=count>0&&count<pages.length;input.closest('summary').querySelector('small').textContent=pages.filter(p=>draft.pages.has(p.id)).length+'/'+pages.length;});document.querySelectorAll('[data-permission-page]').forEach(input=>input.checked=draft.actions[input.dataset.permissionPage].has(input.dataset.permissionAction));});
$('#main').addEventListener('click',event=>{if(event.target.matches('[data-permission-module]'))event.stopPropagation();});

function userTime(value){if(!value)return '—';const date=new Date(value);return Number.isFinite(date.getTime())?date.toLocaleString('en-GB',{timeZone:'Asia/Dhaka'}):'—';}
async function loadAdminUsers(kind){if(adminUserLoading[kind])return;adminUserLoading[kind]=true;adminUserErrors[kind]='';if(adminView&&adminUserPanel===kind)renderAdminView();try{adminUserLists[kind]=await adminRequest(kind==='running'?'running-users':'users');}catch(error){adminUserErrors[kind]=error.message;}finally{adminUserLoading[kind]=false;if(adminView&&adminUserPanel===kind)renderAdminView();}}
function renderAdminUsers(){const kind=adminUserPanel,data=adminUserLists[kind],rows=data?.users||[],running=kind==='running';$('#main').insertAdjacentHTML('beforeend',`<section class="panel admin-user-panel"><div class="admin-user-heading"><div><span class="eyebrow">SUPER ADMIN</span><h3>${running?'Running Users':'User List'} <span class="admin-user-count">${data?rows.length:'…'}</span></h3></div><button type="button" id="refreshAdminUsers" ${adminUserLoading[kind]?'disabled':''}>${adminUserLoading[kind]?'Refreshing…':'Refresh'}</button></div><p class="hint">${running?'Users active within the last 90 seconds. Updates every 15 seconds. Each user appears once, even with multiple open tabs.':'All registered users. Select Running Users to see who is currently active.'}</p><p class="admin-user-updated" role="status">${adminUserErrors[kind]?esc(adminUserErrors[kind]):data?'Updated: '+esc(userTime(data.checkedAt)):'Loading users…'}</p><div class="table-wrap"><table class="admin-user-table"><thead><tr><th>SL</th><th>Username</th><th>Department</th><th>Email ID</th><th>Role</th><th>Status</th><th>${running?'Last active':'Registered'}</th></tr></thead><tbody>${rows.map((user,index)=>`<tr><td>${index+1}</td><td><strong>${esc(user.username)}</strong></td><td>${esc(user.department)}</td><td>${esc(user.email)}</td><td>${user.role==='super_admin'?'Super Admin':'User'}</td><td><span class="user-online-status ${user.running?'online':''}">${user.running?'● Running':user.approved?'Offline':'Pending approval'}</span></td><td>${esc(userTime(running?user.last_seen:user.created_at))}</td></tr>`).join('')||`<tr><td colspan="7" class="empty">${adminUserLoading[kind]?'Loading users…':adminUserErrors[kind]?'Could not load users. Click Refresh to retry.':running?'No users are currently running.':'No registered users yet.'}</td></tr>`}</tbody></table></div></section>`);}
setInterval(()=>{if(adminView&&adminUserPanel==='running'&&!document.hidden)loadAdminUsers('running');},15000);
