'use strict';
let adminView=false,accessInfo={role:'member',department:'',pages:[],revision:0},adminData=null,selectedDepartment='Admin',departmentPanelOpen=false,adminLoading=false;
const permissionDrafts=new Map();
function canPage(id){return accessInfo.role==='super_admin'||accessInfo.pages.includes(id);}
function applyPageLinks(){document.querySelectorAll('[data-open-page]').forEach(node=>{node.hidden=!canPage(node.dataset.openPage);});}
function applyAccess(access){const changed=JSON.stringify(accessInfo)!==JSON.stringify(access);accessInfo=access||{role:'member',department:'',pages:[],revision:0};$('#superAdminButton').hidden=accessInfo.role!=='super_admin';$('#profileRole').textContent=accessInfo.role==='super_admin'?'Super Admin':accessInfo.department||'Member';$('#restoreButton').hidden=accessInfo.role!=='super_admin';if(activePage&&!canPage(activePage)){activePage=null;document.querySelectorAll('dialog[open]').forEach(dialog=>dialog.close());toast('Your page permissions changed.');}if(accessInfo.role!=='super_admin')adminView=false;renderNavigation();applyPageLinks();return changed;}
window.FarnoorAccess={canPage,apply:applyAccess};
const authorizedGoPage=goPage;goPage=function(id){if(!canPage(id)){toast('This page has not been permitted for your department.');return;}adminView=false;authorizedGoPage(id);applyPageLinks();};
const authorizedRenderPage=renderPage;renderPage=function(){if(!activePage||!canPage(activePage)){activePage=null;renderOverview();return;}authorizedRenderPage();applyPageLinks();};
const authorizedOverview=renderOverview;renderOverview=function(){adminView=false;if(accessInfo.role!=='super_admin'&&!accessInfo.pages.length){activePage=null;renderNavigation();$('#main').innerHTML=heading('DEPARTMENT ACCESS','Permission pending','Your Super Admin can tick the pages permitted for your department.')+`<section class="panel access-empty"><h3>${esc(accessInfo.department||'Your department')}</h3><p>No pages have been permitted yet. Contact your Super Admin.</p></section>`;return;}authorizedOverview();applyPageLinks();};
async function adminRequest(route,options={}){const response=await FarnoorAPI.request('/api/admin/'+route,{...options,headers:{'Content-Type':'application/json'}});const body=await response.json();if(!response.ok)throw Object.assign(Error(body.error||'Could not load permissions.'),{status:response.status});return body;}
async function loadAdministration(){if(adminLoading)return;adminLoading=true;try{adminData=await adminRequest('departments');if(adminView)renderAdminView();}catch(error){toast(error.message);if(adminView)$('#adminLoadMessage').textContent=error.message;}finally{adminLoading=false;}}
function draftFor(department){if(!permissionDrafts.has(department)){const saved=adminData.permissions.find(p=>p.department===department);permissionDrafts.set(department,{pages:new Set(saved?.pages||[]),revision:saved?.revision||0,saving:false,dirty:false});}return permissionDrafts.get(department);}
function renderAdminView(){if(accessInfo.role!=='super_admin'){adminView=false;renderOverview();return;}activePage=null;renderNavigation();$('#main').innerHTML=heading('SUPER ADMIN','Super Admin','Manage department access to every subdepartment and page.')+`<button id="adminDepartments" class="admin-department-button" aria-expanded="${departmentPanelOpen}">▦ Department <span>${departmentPanelOpen?'−':'+'}</span></button><div id="adminLoadMessage" role="status">${adminData?'':'Loading departments…'}</div>`;if(!departmentPanelOpen||!adminData)return;const draft=draftFor(selectedDepartment),users=adminData.users.filter(u=>u.department===selectedDepartment),catalog=window.FARNOOR_PAGE_CATALOG;
const moduleNames={hr:'Administration',accounts:'Account'};
const orderedModules=[...DEPARTMENTS.filter(m=>!['admin','sewing'].includes(m.id)),...DEPARTMENTS.filter(m=>['admin','sewing'].includes(m.id))];
function pageRow(page){page={...DEPARTMENTS.flatMap(module=>module.pages).find(item=>item.id===page.id),...page};return `<label class="permission-page" style="--page-shade:${page.shade||'#f3f7ef'}"><span class="permission-page-name"><span class="permission-page-icon">${esc(page.icon||'▤')}</span>${esc(page.name)}${page.hidden?' (Legacy)':''}</span><input type="checkbox" data-permission-page="${page.id}" aria-label="Permit ${esc(page.parent?page.parent+' / ':'')}${esc(page.name)}" ${draft.pages.has(page.id)?'checked':''}></label>`;}
$('#main').insertAdjacentHTML('beforeend',`<section class="permission-layout"><div class="panel permission-editor"><div class="department-dropdown"><label for="permissionDepartment">Department</label><select id="permissionDepartment">${adminData.groups.map(group=>`<optgroup label="${esc(group.name)}">${group.departments.map(name=>`<option value="${esc(name)}" ${name===selectedDepartment?'selected':''}>${esc(name)}</option>`).join('')}</optgroup>`).join('')}</select></div><div class="permission-heading"><div><span class="eyebrow">DEPARTMENT PERMISSIONS</span><h3>${esc(selectedDepartment)}</h3></div><span id="permissionCount">${draft.pages.size} pages permitted</span></div><p class="hint">Tick a box on the right to permit access. Save Permissions applies your changes to users in the selected department.</p><p class="assigned-users">Registered users: ${users.map(u=>esc(u.username)+(u.role==='super_admin'?' (Super Admin · all pages)':'')).join(', ')||'None yet'}</p><div class="permission-controls"><button type="button" id="permitAll">Tick all</button><button type="button" id="permitNone">Untick all</button><button type="button" id="reloadPermissions">Reload permissions</button></div><div class="permission-column-head"><span>Departments, subdepartments and pages</span><span>Allow access</span></div><div class="permission-module-list">${orderedModules.map(module=>{const pages=catalog.filter(p=>p.moduleId===module.id),checked=pages.every(p=>draft.pages.has(p.id)),moduleName=moduleNames[module.id]||module.name,parents=[...new Set(pages.map(p=>p.parent).filter(Boolean))];return `<details class="permission-module" open><summary><span class="permission-module-name"><span class="permission-icon" style="background:${module.color}">${module.icon}</span>${esc(moduleName)}</span><small>${pages.filter(p=>draft.pages.has(p.id)).length}/${pages.length}</small><input type="checkbox" data-permission-module="${module.id}" aria-label="All ${esc(moduleName)} pages" ${checked?'checked':''}></summary><div>${pages.filter(p=>!p.parent).map(pageRow).join('')}${parents.map(parent=>`<details class="permission-subdepartment" open><summary>${esc(parent)}</summary><div>${pages.filter(p=>p.parent===parent).map(pageRow).join('')}</div></details>`).join('')}</div></details>`;}).join('')}</div><div class="permission-save"><span id="permissionSaveStatus" role="status">${draft.dirty?'Unsaved changes':'Saved permissions'}</span><button type="button" class="primary" id="savePermissions" ${draft.saving?'disabled':''}>${draft.saving?'Saving…':'Save Permissions'}</button></div></div></section>`);
document.querySelectorAll('[data-permission-module]').forEach(input=>{const pages=catalog.filter(p=>p.moduleId===input.dataset.permissionModule),count=pages.filter(p=>draft.pages.has(p.id)).length;input.indeterminate=count>0&&count<pages.length;});}
$('#superAdminButton').onclick=()=>{adminView=!adminView;if(!adminView){renderOverview();return;}activePage=null;renderAdminView();loadAdministration();};
$('#main').addEventListener('click',async event=>{if(!adminView)return;const button=event.target.closest('button');if(!button)return;if(button.id==='adminDepartments'){departmentPanelOpen=!departmentPanelOpen;renderAdminView();if(!adminData)loadAdministration();}if(button.dataset.permissionDepartment){selectedDepartment=button.dataset.permissionDepartment;renderAdminView();}if(button.id==='permitAll'||button.id==='permitNone'){const draft=draftFor(selectedDepartment);if(draft.saving)return;draft.pages=new Set(button.id==='permitAll'?window.FARNOOR_PAGE_CATALOG.map(p=>p.id):[]);draft.dirty=true;renderAdminView();}if(button.id==='reloadPermissions'){const draft=draftFor(selectedDepartment);if(draft.saving)return;if(draft.dirty&&!confirm('Discard unsaved permission changes for this department?'))return;permissionDrafts.delete(selectedDepartment);await loadAdministration();}if(button.id==='savePermissions'){const department=selectedDepartment,draft=draftFor(department);if(draft.saving)return;draft.saving=true;renderAdminView();try{const result=await adminRequest('permissions',{method:'POST',body:JSON.stringify({department,pages:[...draft.pages],revision:draft.revision})});draft.revision=result.revision;draft.dirty=false;const saved=adminData.permissions.find(p=>p.department===department);Object.assign(saved,result);toast('Department permissions saved.');}catch(error){toast(error.message);}finally{draft.saving=false;if(adminView)renderAdminView();}}});
$('#main').addEventListener('change',event=>{if(!adminView||!adminData)return;const target=event.target;if(target.id==='permissionDepartment'){selectedDepartment=target.value;renderAdminView();return;}const draft=draftFor(selectedDepartment);if(draft.saving)return;if(target.dataset.permissionPage){if(target.checked)draft.pages.add(target.dataset.permissionPage);else draft.pages.delete(target.dataset.permissionPage);draft.dirty=true;}else if(target.dataset.permissionModule){for(const page of window.FARNOOR_PAGE_CATALOG.filter(p=>p.moduleId===target.dataset.permissionModule)){if(target.checked)draft.pages.add(page.id);else draft.pages.delete(page.id);}draft.dirty=true;}else return;$('#permissionCount').textContent=draft.pages.size+' pages permitted';$('#permissionSaveStatus').textContent='Unsaved changes';document.querySelectorAll('[data-permission-module]').forEach(input=>{const pages=window.FARNOOR_PAGE_CATALOG.filter(p=>p.moduleId===input.dataset.permissionModule),count=pages.filter(p=>draft.pages.has(p.id)).length;input.checked=count===pages.length;input.indeterminate=count>0&&count<pages.length;input.closest('summary').querySelector('small').textContent=count+'/'+pages.length;});document.querySelectorAll('[data-permission-page]').forEach(input=>input.checked=draft.pages.has(input.dataset.permissionPage));});
$('#main').addEventListener('click',event=>{if(event.target.matches('[data-permission-module]'))event.stopPropagation();});
