'use strict';
const PRODUCTION_SECTIONS=['Line-1','Line-2','Line-3','Line-4','Unit-2 Line-1','Unit-2 Line-2','Unit-2 Line-3','Unit-2 Line-4'];
let productionReportMonth='',productionReportEditing=false,productionOrderNames={buyers:[],items:[],styles:[]},productionNamesRequest=null,productionNamesLoadedAt=0;
function productionPageId(section,report=false){return 'schedule-'+(report?'report-':'line-')+(PRODUCTION_SECTIONS.indexOf(section)+1);}
function productionSectionSelect(section,report=false){return `<label class="production-section">Section<select id="productionSection" class="production-section-select" aria-label="Section">${PRODUCTION_SECTIONS.map(name=>`<option value="${esc(name)}" ${name===section?'selected':''} ${FarnoorAccess.canPage(productionPageId(name,report))?'':'disabled'}>${esc(name)}</option>`).join('')}</select></label>`;}
productionIdentity=function(){return `<div class="order-company production-company"><img src="Farnoor_New_Logo.png" alt="Farnoor logo"><div><h3>FARNOOR GARMENTS LTD.</h3><p>1028/1/2 Malibagh Bazar Road, Dhaka-1217</p></div></div><h2 class="account-title">PRODUCTION PLAN</h2><div class="live-clock production-clock"></div>`;};
holidayControls=function(draft){const month=parseScheduleMonth(draft.month);return `<div class="production-controls">${productionSectionSelect(draft.section,activePage.startsWith('schedule-report-'))}<label>Month/Year<input id="productionMonth" aria-label="Month/Year" value="${esc(month.label)}" placeholder="1/26"><span id="productionMonthLabel" hidden>${month.label}</span></label><label>Weekly Holiday<select id="productionWeekly" aria-label="Weekly Holiday">${['None',...WEEKDAYS].map(day=>`<option ${draft.weekly===day?'selected':''}>${day}</option>`).join('')}</select></label><details class="extra-holidays"><summary>Extra Holiday <span id="extraSummary">${draft.extra.length?draft.extra.join(', '):'Select dates'}</span></summary><div class="holiday-options">${Array.from({length:31},(_,i)=>i+1).map(day=>`<label><input type="checkbox" data-extra-holiday="${day}" aria-label="Extra Holiday ${day}" ${day>month.days?'disabled':''} ${draft.extra.includes(day)?'checked':''}>${day}</label>`).join('')}</div></details></div>`;};
async function loadProductionOrderNames(){
 if(productionNamesRequest)return productionNamesRequest;
 if(Date.now()-productionNamesLoadedAt<60000)return;
 productionNamesRequest=(async()=>{try{const response=await FarnoorAPI.request('/api/production/order-options');const body=await response.json();if(!response.ok)throw Error(body.error||'Could not load order names.');for(const key of ['buyers','items','styles'])productionOrderNames[key]=Array.isArray(body[key])?body[key].filter(s=>typeof s==='string'):[];productionNamesLoadedAt=Date.now();}catch(error){if(activePage?.startsWith('schedule-'))toast(error.message);}finally{productionNamesRequest=null;}})();return productionNamesRequest;
}
drawProductionEditor=function(){const draft=currentProductionDraft();$('#main').innerHTML=`<div class="order-actions no-print"><button data-production-action="new">New file</button>${productionReportEditing?'<button data-production-v2="cancel-edit">Back to reports</button>':''}</div><section class="account-paper production-paper printable">${productionIdentity(draft.section)}${holidayControls(draft)}<p class="file-caption">${draft.id?'Editing '+esc(draft.id):'New schedule'}</p>${productionTable(draft,true)}<div class="entry-controls no-print"><button data-production-action="row">+Row</button><button data-production-action="save" id="productionSave" class="primary">Save</button></div><div id="productionCalendar">${calendarTable(draft,true)}</div>${remainingNotice(draft)}<div class="entry-controls no-print"><button data-production-action="save" class="primary">Save</button></div>${productionSignatures()}</section>`;tickClock();loadProductionOrderNames();};
const productionV2Renderer=renderPage;
renderPage=function(){if(activePage?.startsWith('schedule-report-')&&productionReportEditing)drawProductionEditor();else productionV2Renderer();};
function productionReportFiles(section){return scheduleFiles(section).filter(file=>!productionReportMonth||file.month===productionReportMonth).slice().sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt)||b.id.localeCompare(a.id));}
function productionFileActions(file){return `<div class="order-actions no-print production-file-actions">${[['print','Print'],['edit','Edit'],['excel','Excel'],['delete','Delete']].map(([action,label])=>`<button class="${action}-action" data-production-action="${action}" data-schedule-target="${esc(file.id)}" aria-label="${label} ${esc(file.id)}">${label}</button>`).join('')}</div>`;}
drawProductionReport=function(){const section=scheduleSection(),files=productionReportFiles(section);if(!files.some(file=>file.id===selectedSchedule))selectedSchedule=files[0]?.id||null;$('#main').innerHTML=`<div class="production-report-filters no-print">${productionSectionSelect(section,true)}<label>Month/Year<input id="productionReportMonth" aria-label="Report Month/Year" placeholder="1/26 · All months" value="${productionReportMonth?esc(parseScheduleMonth(productionReportMonth).label):''}"></label><button data-production-v2="all-months">All months</button><button data-production-action="new" class="primary">New schedule</button></div><div class="production-report-list">${files.map(file=>`<article class="production-report-document ${file.id===selectedSchedule?'production-print-selected':''}" data-production-file="${esc(file.id)}">${productionFileActions(file)}<section class="account-paper production-paper printable">${productionIdentity(file.section)}<div class="production-report-meta"><span>Section: ${esc(file.section)}</span><span>${parseScheduleMonth(file.month).label}</span><span>Weekly Holiday: ${esc(file.weekly)}</span><span>Extra Holiday: ${file.extra.join(', ')||'None'}</span></div><p class="file-caption">${esc(file.id)} · Saved ${new Date(file.createdAt).toLocaleString('en-GB',{timeZone:'Asia/Dhaka'})}</p>${productionTable(file,false)}${calendarTable(file,false)}${remainingNotice(file)}${productionSignatures()}</section></article>`).join('')||'<div class="empty">No saved schedules match this section and month.</div>'}</div>`;tickClock();};
editProduction=function(){const section=scheduleSection(),file=scheduleFiles(section).find(f=>f.id===selectedSchedule);if(!file){toast('Select a saved schedule first.');return;}productionDrafts.set(section,structuredClone(file));productionReportEditing=true;drawProductionEditor();};
saveProduction=async function(){const button=$('#productionSave');if(button?.dataset.saving==='true')return;if(button)button.dataset.saving='true';try{const original=currentProductionDraft(),draft=validateProductionPlan(original);validateProductionActuals(draft);const next=structuredClone(state);next.productionSchedules||=[];const index=next.productionSchedules.findIndex(file=>file.id===draft.id);if(draft.id&&index<0)throw Error('This schedule was removed. Refresh before saving.');const file={...structuredClone(draft),id:draft.id||`PLAN-${Date.now()}-${crypto.randomUUID().slice(0,6)}`,createdAt:index>=0?next.productionSchedules[index].createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};if(index>=0)next.productionSchedules[index]=file;else next.productionSchedules.unshift(file);if(await commit(next)){selectedSchedule=file.id;productionDrafts.delete(draft.section);productionReportEditing=false;productionReportMonth='';const report=productionPageId(draft.section,true);if(FarnoorAccess.canPage(report))goPage(report);else{productionDrafts.set(draft.section,structuredClone(file));drawProductionEditor();}toast('Production schedule saved');}}catch(error){toast(error.message);}finally{if(button)delete button.dataset.saving;}};
const productionV2GoPage=goPage;
goPage=function(id){if(id!==activePage)productionReportEditing=false;productionV2GoPage(id);};
function productionComplete(input,event){const col=Number(input.dataset.planCol);if(![0,1,2].includes(col)||event.inputType?.startsWith('delete'))return;const typed=input.value;if(typed.trim().length<2)return;const key=['buyers','items','styles'][col],local=(state.orderFiles||[]).flatMap(file=>file.rows.map(row=>row[['buyer','item','style'][col]])),names=[...new Set([...productionOrderNames[key],...local])].filter(value=>typeof value==='string');const query=typed.toLocaleLowerCase(),match=names.find(value=>value.toLocaleLowerCase().startsWith(query))||names.find(value=>value.toLocaleLowerCase().includes(query));if(match&&match!==typed){input.value=match;const start=match.toLocaleLowerCase().indexOf(query);input.setSelectionRange(start===0?typed.length:0,match.length);}}
$('#main').addEventListener('input',event=>{if(event.target.matches('[data-plan-row]'))productionComplete(event.target,event);},true);
$('#main').addEventListener('change',event=>{const input=event.target;if(input.id==='productionSection'){event.stopImmediatePropagation();const report=activePage.startsWith('schedule-report-'),id=productionPageId(input.value,report);if(!FarnoorAccess.canPage(id)){input.value=scheduleSection();toast('This section has not been permitted.');return;}productionReportEditing=false;goPage(id);}if(input.id==='productionReportMonth'){event.stopImmediatePropagation();try{const month=input.value.trim()?parseScheduleMonth(input.value):null;productionReportMonth=month?`${month.month}/${month.year}`:'';drawProductionReport();}catch(error){toast(error.message);}}},true);
$('#main').addEventListener('keydown',event=>{if(event.target.id==='productionReportMonth'&&event.key==='Enter'){event.preventDefault();event.target.dispatchEvent(new Event('change',{bubbles:true}));}},true);
$('#main').addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;const extra=button.dataset.productionV2;if(extra){event.preventDefault();event.stopImmediatePropagation();if(extra==='all-months'){productionReportMonth='';drawProductionReport();}if(extra==='cancel-edit'){productionReportEditing=false;drawProductionReport();}return;}if(button.dataset.scheduleTarget){selectedSchedule=button.dataset.scheduleTarget;document.querySelectorAll('[data-production-file]').forEach(node=>node.classList.toggle('production-print-selected',node.dataset.productionFile===selectedSchedule));}if(button.dataset.productionAction==='new'&&activePage.startsWith('schedule-report-')){event.preventDefault();event.stopImmediatePropagation();const section=scheduleSection(),draft=productionDrafts.get(section);if(draft?.rows.some(row=>Object.values(row).some(value=>String(value).trim()))&&!confirm('Discard the current unsaved production plan?'))return;productionDrafts.set(section,newProductionDraft(section));const editor=productionPageId(section);if(FarnoorAccess.canPage(editor))goPage(editor);else{productionReportEditing=true;drawProductionEditor();}}},true);
