'use strict';
let accountRecoveryToken='',accountRecoveryFields=[];
function resetRecovery(){accountRecoveryToken='';accountRecoveryFields=[];for(const id of ['recoveryStart','recoveryCodeForm','recoveryChangeForm'])el(id).reset();el('recoveryStart').hidden=false;el('recoveryCodeForm').hidden=true;el('recoveryChangeForm').hidden=true;el('recoverySummary').textContent='';}
const recoveryLoginView=loginView;
loginView=function(){el('recovery').hidden=true;resetRecovery();recoveryLoginView();};
el('openForgot').onclick=()=>{resetRecovery();el('loginForm').hidden=true;el('registration').hidden=true;el('recovery').hidden=false;message('');el('recoveryAccount').focus();};
el('backFromForgot').onclick=loginView;
el('changeRecovery').onclick=()=>{resetRecovery();message('');el('recoveryAccount').focus();};
el('recoveryStart').onsubmit=event=>{event.preventDefault();const fields=[...document.querySelectorAll('[name="recoveryField"]:checked')].map(input=>input.value);if(!fields.length){message('Tick UserName, Password or Email.');return;}act(async()=>{const account=el('recoveryAccount').value.trim(),result=await request('recovery/start',{account,fields,previousToken:accountRecoveryToken});accountRecoveryToken=result.recoveryToken;accountRecoveryFields=fields;el('recoverySummary').textContent=account+' · '+fields.map(f=>({username:'UserName',password:'Password',email:'Email'}[f])).join(', ');el('recoveryStart').hidden=true;el('recoveryCodeForm').hidden=false;message(result.message,true);el('recoveryCode').focus();});};
el('recoveryCodeForm').onsubmit=event=>{event.preventDefault();act(async()=>{const code=el('recoveryCode').value.replace(/[০-৯]/g,c=>'০১২৩৪৫৬৭৮৯'.indexOf(c));await request('recovery/verify',{recoveryToken:accountRecoveryToken,code});el('recoveryCode').value='';el('recoveryCodeForm').hidden=true;el('recoveryChangeForm').hidden=false;for(const [field,id]of [['username','recoverUsername'],['email','recoverEmail'],['password','recoverPassword'],['password','recoverConfirm']]){const input=el(id),chosen=accountRecoveryFields.includes(field);input.disabled=!chosen;input.required=chosen;input.closest('.recovery-change').hidden=!chosen;input.value='';}message('Code verified. Enter the new details.',true);el('recoveryChangeForm').querySelector('input:not(:disabled)').focus();});};
el('recoverPassword').oninput=el('recoverConfirm').oninput=()=>el('recoverConfirm').setCustomValidity('');
el('recoveryChangeForm').onsubmit=event=>{event.preventDefault();if(accountRecoveryFields.includes('password')&&el('recoverPassword').value!==el('recoverConfirm').value){el('recoverConfirm').setCustomValidity('Passwords must match.');el('recoverConfirm').reportValidity();return;}act(async()=>{const result=await request('recovery/complete',{recoveryToken:accountRecoveryToken,...Object.fromEntries(new FormData(event.target))});loginView();message(result.message,!result.partial);el('loginUsername').focus();});};
