'use strict';
const WEEKDAYS=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const BANGLA_MONTHS=['জানুয়ারী','ফেব্রুয়ারী','মার্চ','এপ্রিল','মে','জুন','জুলাই','আগস্ট','সেপ্টেম্বর','অক্টোবর','নভেম্বর','ডিসেম্বর'];
const PLAN_FIELDS=[['buyer','BUYER'],['item','ITEM'],['style','STIYLE'],['orderQty','ORDER QTY'],['excess','EXCESS'],['totalQty','TOTAL QTY'],['firstTarget','FAST DAY TERGET'],['dailyTarget','DAILY TERGET'],['startDate','TERGET START DATE'],['remarks','REMARKS']];
function scheduleDigits(value){return String(value).trim().replace(/[০-৯]/g,c=>'০১২৩৪৫৬৭৮৯'.indexOf(c)).replaceAll(',','');}
function parseScheduleMonth(value){const match=scheduleDigits(value).match(/^(\d{1,2})[/-](\d{2}|\d{4})$/);if(!match)throw Error('Month/Year লিখুন যেমন 1/26।');const month=Number(match[1]),year=Number(match[2])+(match[2].length===2?2000:0);if(month<1||month>12||year<1900||year>2199)throw Error('সঠিক Month/Year দিন।');return {month,year,days:new Date(year,month,0).getDate(),label:BANGLA_MONTHS[month-1]+'-'+year};}
function scheduleInteger(value,label,zero=true){const raw=scheduleDigits(value);if(!/^\d+$/.test(raw)||!Number.isSafeInteger(Number(raw))||Number(raw)>1000000000||(!zero&&Number(raw)===0))throw Error(label+' must be '+(zero?'a non-negative':'a positive')+' whole number.');return Number(raw);}
function excessPercent(row){if(!String(row.orderQty).trim()||!String(row.totalQty).trim())return null;const order=Number(scheduleDigits(row.orderQty)),total=Number(scheduleDigits(row.totalQty));return order>0&&Number.isFinite(total)?(total-order)/order*100:null;}
function signedPercent(value){return value===null?'—':(value>0?'+':'')+value.toFixed(2)+'%';}
function validateProductionPlan(draft){const month=parseScheduleMonth(draft.month);if(!WEEKDAYS.includes(draft.weekly)&&draft.weekly!=='None')throw Error('Select a weekly holiday.');if(!Array.isArray(draft.extra)||draft.extra.some(day=>!Number.isInteger(day)||day<1||day>month.days))throw Error('Extra holidays must be valid days of the selected month.');const rows=draft.rows.filter(row=>Object.values(row).some(value=>String(value).trim())).map(row=>{if(!row.buyer.trim()||!row.item.trim()||!row.style.trim())throw Error('Every filled row needs BUYER, ITEM and STIYLE.');const startDate=normalizeDate(row.startDate);const parts=startDate.split('/').map(Number);if(parts[1]!==month.month||parts[2]!==month.year)throw Error('TERGET START DATE must be inside the selected month.');return {...row,buyer:row.buyer.trim(),item:row.item.trim(),style:row.style.trim(),remarks:row.remarks.trim(),orderQty:scheduleInteger(row.orderQty,'ORDER QTY',false),totalQty:scheduleInteger(row.totalQty,'TOTAL QTY',false),firstTarget:scheduleInteger(row.firstTarget,'FAST DAY TERGET'),dailyTarget:scheduleInteger(row.dailyTarget,'DAILY TERGET',false),startDate};});if(!rows.length)throw Error('Enter at least one production plan row.');return {...draft,rows};}
function generateProductionCalendar(draft){const month=parseScheduleMonth(draft.month),plans=draft.rows.map(row=>{try{const parts=normalizeDate(row.startDate).split('/').map(Number);if(parts[1]!==month.month||parts[2]!==month.year)return null;return {day:parts[0],remaining:scheduleInteger(row.totalQty,'TOTAL QTY'),first:scheduleInteger(row.firstTarget,'FAST DAY TERGET'),daily:scheduleInteger(row.dailyTarget,'DAILY TERGET'),started:false};}catch{return null;}}).filter(Boolean);const calendar=[];
 for(let day=1;day<=month.days;day++){const date=`${String(day).padStart(2,'0')}-${String(month.month).padStart(2,'0')}-${month.year}`,weekly=WEEKDAYS[new Date(month.year,month.month-1,day).getDay()]===draft.weekly,holiday=draft.extra.includes(day)?'Holiday':weekly?'Weekly Holiday':'';let target=0;if(!holiday)for(const plan of plans){if(day<plan.day||plan.remaining<=0)continue;const count=Math.min(plan.remaining,plan.started?plan.daily:plan.first);target+=count;plan.remaining-=count;plan.started=true;}const actual=draft.journal?.[date]||{},hours=holiday?0:Number(actual.hours??10),output=holiday?0:Number(scheduleDigits(actual.output||0));calendar.push({day,date,holiday,target,hours,output,achievement:target?output/target*100:null,hourlyTarget:hours>0?target/hours:null,remarks:String(actual.remarks||'')});}
 return {month,calendar,unallocated:plans.reduce((sum,plan)=>sum+plan.remaining,0)};
}
function validateProductionActuals(draft){const result=generateProductionCalendar(draft);for(const row of result.calendar){if(row.holiday)continue;const actual=draft.journal?.[row.date]||{};scheduleInteger(actual.output||'0','DAILY OUTPUT');const hours=Number(actual.hours??10);if(!Number.isFinite(hours)||hours<=0||hours>24)throw Error('TOTAL HOURS must be greater than 0 and at most 24.');if(String(actual.remarks||'').length>500)throw Error('Daily remarks are too long.');}return result;}
