/* Minimal dependency-free Office Open XML workbook writer, with numeric cells. */
function makeXlsx(matrix,title){
 const xml=value=>String(value).replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
 const rows=matrix.map((row,r)=>`<row r="${r+1}">${row.map((value,c)=>{const ref=String.fromCharCode(65+c)+(r+1);return typeof value==='number'?`<c r="${ref}"><v>${value}</v></c>`:`<c r="${ref}" t="inlineStr"><is><t xml:space="preserve">${xml(value)}</t></is></c>`;}).join('')}</row>`).join('');
 const files={
 '[Content_Types].xml':'<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>',
 '_rels/.rels':'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>',
 'xl/workbook.xml':`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="${xml(title)}" sheetId="1" r:id="rId1"/></sheets></workbook>`,
 'xl/_rels/workbook.xml.rels':'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>',
 'xl/worksheets/sheet1.xml':`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><cols><col min="1" max="1" width="8" customWidth="1"/><col min="2" max="11" width="24" customWidth="1"/></cols><sheetData>${rows}</sheetData></worksheet>`};
 const encoder=new TextEncoder(),parts=[],central=[];let offset=0;
 const crc=data=>{let n=0xffffffff;for(const byte of data){n^=byte;for(let k=0;k<8;k++)n=(n>>>1)^((n&1)?0xedb88320:0);}return (n^0xffffffff)>>>0;};
 const header=(size)=>({bytes:new Uint8Array(size),view:null});
 for(const [name,content]of Object.entries(files)){const filename=encoder.encode(name),data=encoder.encode(content),checksum=crc(data),local=header(30);local.view=new DataView(local.bytes.buffer);local.view.setUint32(0,0x04034b50,true);local.view.setUint16(4,20,true);local.view.setUint32(14,checksum,true);local.view.setUint32(18,data.length,true);local.view.setUint32(22,data.length,true);local.view.setUint16(26,filename.length,true);parts.push(local.bytes,filename,data);const cd=header(46);cd.view=new DataView(cd.bytes.buffer);cd.view.setUint32(0,0x02014b50,true);cd.view.setUint16(4,20,true);cd.view.setUint16(6,20,true);cd.view.setUint32(16,checksum,true);cd.view.setUint32(20,data.length,true);cd.view.setUint32(24,data.length,true);cd.view.setUint16(28,filename.length,true);cd.view.setUint32(42,offset,true);central.push(cd.bytes,filename);offset+=30+filename.length+data.length;}
 const centralSize=central.reduce((n,a)=>n+a.length,0),end=header(22);end.view=new DataView(end.bytes.buffer);end.view.setUint32(0,0x06054b50,true);end.view.setUint16(8,Object.keys(files).length,true);end.view.setUint16(10,Object.keys(files).length,true);end.view.setUint32(12,centralSize,true);end.view.setUint32(16,offset,true);const output=new Uint8Array(offset+centralSize+22);let cursor=0;for(const piece of [...parts,...central,end.bytes]){output.set(piece,cursor);cursor+=piece.length;}return output;
}
